"""Cross-language watermark conformance (GAP-9).

ClientSynth signs the population file; Cosolvent verifies it at the ingest
boundary. Both sides must canonicalise a record to *byte-identical* bytes —
any drift in key ordering, separators, escaping, or number formatting would
silently reject every synthetic record in production.

The fixture is generated by ClientSynth
(`npx tsx scripts/watermark-conformance.ts <out.json>`) and committed here, so
this test fails loudly if either implementation changes its canonical form.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from app.core import watermark

FIXTURE = Path(__file__).resolve().parents[1] / "fixtures" / "watermark_vectors.json"


def _load() -> dict:
    if not FIXTURE.exists():  # pragma: no cover - guards a missing regeneration step
        pytest.skip(f"conformance fixture missing: {FIXTURE}")
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


def _vectors() -> list[dict]:
    return _load()["vectors"]


def test_algo_matches() -> None:
    assert _load()["algo"] == watermark.WATERMARK_ALGO


@pytest.mark.parametrize("vector", _vectors(), ids=lambda v: v["name"])
def test_canonical_payload_is_byte_identical(vector: dict) -> None:
    """The exact bytes each side signs must agree — asserted directly so a
    divergence points at the canonical form rather than at an opaque HMAC."""
    record = vector["record"]
    ours = watermark._canonical_payload(record).decode("utf-8")
    assert ours == vector["canonical"]


@pytest.mark.parametrize("vector", _vectors(), ids=lambda v: v["name"])
def test_signature_matches(vector: dict) -> None:
    secret = _load()["secret"]
    assert watermark.sign(vector["record"], secret) == vector["signature"]


@pytest.mark.parametrize("vector", _vectors(), ids=lambda v: v["name"])
def test_clientsynth_records_verify(vector: dict) -> None:
    """The end-to-end property: a record ClientSynth stamped passes our gate."""
    assert watermark.verify(vector["record"], _load()["secret"]) is True


@pytest.mark.parametrize("vector", _vectors(), ids=lambda v: v["name"])
def test_tampering_a_clientsynth_record_is_detected(vector: dict) -> None:
    tampered = json.loads(json.dumps(vector["record"]))
    tampered["fields"]["injected_by_attacker"] = "x"
    assert watermark.verify(tampered, _load()["secret"]) is False


def test_wrong_secret_rejects_every_vector() -> None:
    for vector in _vectors():
        assert watermark.verify(vector["record"], "not-the-shared-secret") is False
