"""Generate typed API client functions from the FrontendIR.

Emits:
- ``src/generated/api/client.ts`` — central fetch wrapper
- ``src/generated/api/{module}.ts`` — per-module typed functions
"""

from __future__ import annotations

from collections import defaultdict

from ..ir import FrontendIR, OperationIR
from ..naming import api_client_filename

_HEADER = """\
// AUTO-GENERATED by Cosolvent Frontend Compiler v{version}
// spec_hash: {hash}
// DO NOT EDIT — changes will be overwritten on next compile
"""


def emit_api_clients(ir: FrontendIR) -> dict[str, str]:
    files: dict[str, str] = {}
    files["src/generated/api/client.ts"] = _base_client(ir)

    ops_by_module: dict[str, list[OperationIR]] = defaultdict(list)
    for op in ir.operations:
        ops_by_module[op.module].append(op)

    for module, ops in sorted(ops_by_module.items()):
        filename = api_client_filename(module)
        files[f"src/generated/api/{filename}"] = _module_client(ir, module, ops)

    return files


def _base_client(ir: FrontendIR) -> str:
    return _HEADER.format(version=ir.generator_version, hash=ir.spec_hash) + """
const API_BASE = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:18000";

export class ApiError extends Error {
  constructor(
    public status: number,
    public body: unknown,
    message?: string,
  ) {
    super(message ?? `API error ${status}`);
    this.name = "ApiError";
  }
}

export async function apiFetch<T>(
  path: string,
  init?: RequestInit,
): Promise<T> {
  const url = `${API_BASE}${path}`;
  const res = await fetch(url, {
    ...init,
    credentials: "include",
    headers: {
      "Content-Type": "application/json",
      ...init?.headers,
    },
  });
  if (!res.ok) {
    const body = await res.json().catch(() => null);
    throw new ApiError(res.status, body, body?.detail);
  }
  return res.json();
}

export async function apiFetchVoid(
  path: string,
  init?: RequestInit,
): Promise<void> {
  const url = `${API_BASE}${path}`;
  const res = await fetch(url, {
    ...init,
    credentials: "include",
    headers: {
      "Content-Type": "application/json",
      ...init?.headers,
    },
  });
  if (!res.ok) {
    const body = await res.json().catch(() => null);
    throw new ApiError(res.status, body, body?.detail);
  }
}

export async function apiUpload<T>(
  path: string,
  formData: FormData,
): Promise<T> {
  const url = `${API_BASE}${path}`;
  const res = await fetch(url, {
    method: "POST",
    credentials: "include",
    body: formData,
  });
  if (!res.ok) {
    const body = await res.json().catch(() => null);
    throw new ApiError(res.status, body, body?.detail);
  }
  return res.json();
}
"""


def _module_client(ir: FrontendIR, module: str, ops: list[OperationIR]) -> str:
    lines: list[str] = [_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)]

    type_imports = _collect_type_imports(ops)
    if type_imports:
        joined = ", ".join(sorted(type_imports))
        lines.append(f'import type {{ {joined} }} from "../types";')

    lines.append('import { apiFetch, apiFetchVoid, apiUpload } from "./client";')
    lines.append("")

    for op in sorted(ops, key=lambda o: o.id):
        lines.append(_render_function(op))

    return "\n".join(lines) + "\n"


def _render_function(op: OperationIR) -> str:
    fn_name = op.id
    params: list[str] = []
    path_expr = _build_path_expr(op)
    return_type = _response_type(op)

    for pp in op.path_params:
        params.append(f"{pp}: string")

    for qp in op.query_params:
        opt = "?" if not qp.required else ""
        params.append(f"{qp.name}{opt}: {qp.ts_type}")

    if op.request_schema:
        params.append(f"body: {op.request_schema.name}")

    params_str = ", ".join(params)

    lines: list[str] = []
    lines.append(f"export function {fn_name}({params_str}) {{")

    query_parts = [qp for qp in op.query_params]
    if query_parts:
        lines.append("  const params = new URLSearchParams();")
        for qp in query_parts:
            if qp.required:
                lines.append(f'  params.set("{qp.name}", String({qp.name}));')
            else:
                lines.append(
                    f"  if ({qp.name} !== undefined) "
                    f'params.set("{qp.name}", String({qp.name}));'
                )
        # Only append ``?<query>`` when there's actually content — otherwise
        # the URL trails with a bare ``?`` which some servers normalise weirdly.
        lines.append("  const queryString = params.toString();")
        path_with_query = (
            f'`{path_expr}${{queryString ? `?${{queryString}}` : ""}}`'
        )
    else:
        path_with_query = f"`{path_expr}`" if "$" in path_expr else f'"{op.path}"'

    if op.method == "GET":
        lines.append(f"  return apiFetch<{return_type}>({path_with_query});")
    elif op.method == "DELETE":
        lines.append(f"  return apiFetchVoid({path_with_query}, {{ method: \"DELETE\" }});")
    elif op.request_schema:
        lines.append(
            f"  return apiFetch<{return_type}>({path_with_query}, {{"
        )
        lines.append(f'    method: "{op.method}",')
        lines.append("    body: JSON.stringify(body),")
        lines.append("  });")
    else:
        lines.append(
            f"  return apiFetch<{return_type}>({path_with_query}, "
            f'{{ method: "{op.method}" }});'
        )

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _build_path_expr(op: OperationIR) -> str:
    path = op.path
    for pp in op.path_params:
        path = path.replace("{" + pp + "}", "${" + pp + "}")
    return path


def _response_type(op: OperationIR) -> str:
    if op.response_schema:
        return op.response_schema.name
    return "Record<string, unknown>"


def _collect_type_imports(ops: list[OperationIR]) -> set[str]:
    imports: set[str] = set()
    for op in ops:
        if op.request_schema:
            imports.add(op.request_schema.name)
        if op.response_schema:
            imports.add(op.response_schema.name)
    return imports
