"""Minimal API explorer page — invoke any generated OpenAPI operation."""

from __future__ import annotations

from ..ir import FrontendIR

_HEADER = """\
// AUTO-GENERATED by Cosolvent Frontend Compiler v{version}
// spec_hash: {hash}
// DO NOT EDIT — changes will be overwritten on next compile
"""


def emit_api_explorer_page(ir: FrontendIR) -> dict[str, str]:
    """Single dashboard page that lists all operations and runs them against the backend."""
    header = _HEADER.format(version=ir.generator_version, hash=ir.spec_hash)
    page = (
        header
        + '''
"use client";

import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import {
  operationsManifest,
  type OperationManifestEntry,
} from "@/generated/operations-manifest";

const API_BASE = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:18000";

function buildUrl(
  op: OperationManifestEntry,
  pathVals: Record<string, string>,
  queryVals: Record<string, string>,
): string {
  let path = op.path;
  for (const key of op.pathParams) {
    const v = pathVals[key] ?? "";
    path = path.replace(`{${key}}`, encodeURIComponent(v));
  }
  const params = new URLSearchParams();
  for (const q of op.queryParams) {
    const v = queryVals[q.name];
    if (v !== undefined && v !== "") params.set(q.name, v);
  }
  const qs = params.toString();
  return `${API_BASE}${path}${qs ? `?${qs}` : ""}`;
}

export default function ApiExplorerPage() {
  const [filter, setFilter] = useState("");
  const [moduleFilter, setModuleFilter] = useState<string>("all");
  const [selectedId, setSelectedId] = useState<string>(operationsManifest[0]?.id ?? "");
  const [pathVals, setPathVals] = useState<Record<string, string>>({});
  const [queryVals, setQueryVals] = useState<Record<string, string>>({});
  const [jsonBody, setJsonBody] = useState<string>('{}');
  const [mpPrivacy, setMpPrivacy] = useState("private");
  const [mpCategory, setMpCategory] = useState("onboarding");
  const [mpProfileId, setMpProfileId] = useState("");
  const [mpFile, setMpFile] = useState<File | null>(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<string | null>(null);
  const [status, setStatus] = useState<number | null>(null);

  const modules = useMemo(() => {
    const s = new Set<string>();
    for (const op of operationsManifest) s.add(op.module);
    return ["all", ...Array.from(s).sort()];
  }, []);

  const filtered = useMemo(() => {
    const f = filter.trim().toLowerCase();
    return operationsManifest.filter((op) => {
      if (moduleFilter !== "all" && op.module !== moduleFilter) return false;
      if (!f) return true;
      return (
        op.path.toLowerCase().includes(f) ||
        op.id.toLowerCase().includes(f) ||
        op.method.toLowerCase().includes(f)
      );
    });
  }, [filter, moduleFilter]);

  const selected = useMemo(
    () => operationsManifest.find((o) => o.id === selectedId) ?? null,
    [selectedId],
  );

  async function execute() {
    if (!selected) return;
    setLoading(true);
    setResult(null);
    setStatus(null);
    try {
      const url = buildUrl(selected, pathVals, queryVals);
      if (selected.bodyKind === "multipart") {
        const fd = new FormData();
        fd.append("privacy", mpPrivacy);
        fd.append("category", mpCategory);
        if (mpProfileId) fd.append("profile_id", mpProfileId);
        if (mpFile) fd.append("file", mpFile);
        const res = await fetch(url, {
          method: "POST",
          credentials: "include",
          body: fd,
        });
        setStatus(res.status);
        const text = await res.text();
        try {
          setResult(JSON.stringify(JSON.parse(text), null, 2));
        } catch {
          setResult(text || "(empty body)");
        }
        return;
      }

      const init: RequestInit = { credentials: "include" };
      if (selected.method === "GET") {
        const res = await fetch(url, init);
        setStatus(res.status);
        const text = await res.text();
        try {
          setResult(text ? JSON.stringify(JSON.parse(text), null, 2) : "(empty body)");
        } catch {
          setResult(text);
        }
        return;
      }

      if (selected.method === "DELETE") {
        const res = await fetch(url, { ...init, method: "DELETE" });
        setStatus(res.status);
        const text = await res.text();
        setResult(text ? text : "(no content)");
        return;
      }

      init.method = selected.method;
      const trimmed = jsonBody.trim();
      if (trimmed) {
        init.headers = { "Content-Type": "application/json" };
        init.body = trimmed;
      }
      const res = await fetch(url, init);
      setStatus(res.status);
      const text = await res.text();
      try {
        setResult(text ? JSON.stringify(JSON.parse(text), null, 2) : "(empty body)");
      } catch {
        setResult(text || "(empty body)");
      }
    } catch (e: unknown) {
      setResult(e instanceof Error ? e.message : String(e));
      setStatus(null);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">API explorer</h1>
        <p className="text-muted-foreground">
          Minimal UI for every OpenAPI operation (session cookies sent to {API_BASE}).
        </p>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>Operations</CardTitle>
            <CardDescription>
              {operationsManifest.length} operations — filter and select one to run.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            <div className="flex flex-col gap-2 sm:flex-row">
              <Input
                placeholder="Filter by path, id, or method…"
                value={filter}
                onChange={(e) => setFilter(e.target.value)}
              />
              <select
                className="h-10 rounded-md border border-input bg-background px-3 text-sm"
                value={moduleFilter}
                onChange={(e) => setModuleFilter(e.target.value)}
              >
                {modules.map((m) => (
                  <option key={m} value={m}>
                    {m === "all" ? "All modules" : m}
                  </option>
                ))}
              </select>
            </div>
            <div className="max-h-80 overflow-auto rounded-md border">
              {filtered.map((op) => (
                <button
                  key={op.id}
                  type="button"
                  onClick={() => {
                    setSelectedId(op.id);
                    setPathVals({});
                    setQueryVals({});
                  }}
                  className={
                    "flex w-full flex-col items-start gap-0.5 border-b px-3 py-2 text-left text-sm last:border-b-0 hover:bg-muted/60 " +
                    (op.id === selectedId ? "bg-muted" : "")
                  }
                >
                  <span className="font-mono text-xs text-muted-foreground">
                    {op.method} · {op.module}
                  </span>
                  <span className="break-all">{op.path}</span>
                </button>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Request</CardTitle>
            <CardDescription>
              {selected ? (
                <>
                  <span className="font-mono text-sm">{selected.method}</span>{" "}
                  <span className="break-all">{selected.path}</span>
                  {selected.authRequired ? (
                    <span className="ml-2 rounded bg-amber-500/20 px-1.5 py-0.5 text-xs">
                      auth
                    </span>
                  ) : null}
                </>
              ) : (
                "Select an operation"
              )}
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {selected &&
              selected.pathParams.map((name) => (
                <div key={name} className="space-y-1">
                  <Label htmlFor={`p-${name}`}>Path: {`{${name}}`}</Label>
                  <Input
                    id={`p-${name}`}
                    value={pathVals[name] ?? ""}
                    onChange={(e) =>
                      setPathVals((prev) => ({ ...prev, [name]: e.target.value }))
                    }
                    placeholder={name}
                  />
                </div>
              ))}
            {selected &&
              selected.queryParams.map((q) => (
                <div key={q.name} className="space-y-1">
                  <Label htmlFor={`q-${q.name}`}>
                    Query: {q.name}
                    {!q.required ? " (optional)" : ""}
                  </Label>
                  <Input
                    id={`q-${q.name}`}
                    value={queryVals[q.name] ?? ""}
                    onChange={(e) =>
                      setQueryVals((prev) => ({ ...prev, [q.name]: e.target.value }))
                    }
                  />
                </div>
              ))}
            {selected && selected.bodyKind === "json" ? (
              <div className="space-y-1">
                <Label htmlFor="json-body">JSON body</Label>
                <textarea
                  id="json-body"
                  className="min-h-[140px] w-full rounded-md border border-input bg-background px-3 py-2 font-mono text-sm"
                  value={jsonBody}
                  onChange={(e) => setJsonBody(e.target.value)}
                />
              </div>
            ) : null}
            {selected && selected.bodyKind === "multipart" ? (
              <div className="space-y-3 rounded-md border p-3">
                <p className="text-sm text-muted-foreground">Multipart (file upload)</p>
                <div className="space-y-1">
                  <Label>privacy</Label>
                  <Input value={mpPrivacy} onChange={(e) => setMpPrivacy(e.target.value)} />
                </div>
                <div className="space-y-1">
                  <Label>category</Label>
                  <Input value={mpCategory} onChange={(e) => setMpCategory(e.target.value)} />
                </div>
                <div className="space-y-1">
                  <Label>profile_id (optional)</Label>
                  <Input
                    value={mpProfileId}
                    onChange={(e) => setMpProfileId(e.target.value)}
                  />
                </div>
                <div className="space-y-1">
                  <Label>file</Label>
                  <Input
                    type="file"
                    onChange={(e) => setMpFile(e.target.files?.[0] ?? null)}
                  />
                </div>
              </div>
            ) : null}
            <Button onClick={execute} disabled={loading || !selected}>
              {loading ? "Running…" : "Send request"}
            </Button>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Response</CardTitle>
          <CardDescription>
            {status !== null ? `HTTP ${status}` : "—"}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <pre className="max-h-96 overflow-auto rounded-md border bg-muted/40 p-4 text-xs">
            {result ?? "—"}
          </pre>
        </CardContent>
      </Card>
    </div>
  );
}
'''
    )
    return {"src/app/(dashboard)/dev/api-explorer/page.tsx": page}
