"""Generate React components from the FrontendIR.

Emits:
- Field renderer (maps IR field types to React components)
- Profile form (tabbed by section, wired to hooks)
- Sidebar layout
- Header
- Search filters
- Profile card
- shadcn/ui primitives
"""

from __future__ import annotations

from ..ir import FrontendIR

_HEADER = """\
// AUTO-GENERATED by Cosolvent Frontend Compiler v{version}
// spec_hash: {hash}
// DO NOT EDIT — changes will be overwritten on next compile
"""


def emit_components(ir: FrontendIR) -> dict[str, str]:
    files: dict[str, str] = {}

    # Layout components
    files["src/components/layouts/app-sidebar.tsx"] = _app_sidebar(ir)
    files["src/components/layouts/header.tsx"] = _header(ir)

    # Form components
    files["src/components/forms/field-renderer.tsx"] = _field_renderer(ir)
    files["src/components/forms/profile-form.tsx"] = _profile_form(ir)

    # Shared components
    files["src/components/shared/search-filters.tsx"] = _search_filters(ir)
    files["src/components/shared/profile-card.tsx"] = _profile_card(ir)

    # shadcn/ui primitives
    files.update(_shadcn_ui_components())

    return files


# ── Layout components ─────────────────────────────────────────────────


def _app_sidebar(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

import Link from "next/link";
import {{ usePathname }} from "next/navigation";
import {{ cn }} from "@/lib/utils";
import {{ navigationItems, marketplaceName }} from "@/generated/navigation";

export function AppSidebar() {{
  const pathname = usePathname();

  return (
    <aside className="hidden w-64 shrink-0 border-r bg-sidebar lg:block">
      <div className="flex h-14 items-center border-b px-4">
        <Link href="/" className="text-lg font-semibold text-sidebar-foreground">
          {{marketplaceName}}
        </Link>
      </div>
      <nav className="space-y-1 p-3">
        {{navigationItems.map((item) => {{
          const Icon = item.icon;
          const isActive =
            pathname === item.route ||
            (item.route !== "/" && pathname.startsWith(item.route));
          return (
            <Link
              key={{item.route}}
              href={{item.route}}
              className={{cn(
                "flex items-center gap-3 rounded-md px-3 py-2 text-sm font-medium transition-colors",
                isActive
                  ? "bg-sidebar-accent text-sidebar-accent-foreground"
                  : "text-sidebar-foreground hover:bg-sidebar-accent/50",
              )}}
            >
              <Icon className="h-4 w-4" />
              {{item.label}}
            </Link>
          );
        }})}}
      </nav>
    </aside>
  );
}}
"""


def _header(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

import {{ useRouter }} from "next/navigation";
import {{ Button }} from "@/components/ui/button";

export function Header() {{
  const router = useRouter();

  async function handleLogout() {{
    try {{
      await fetch(
        (process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:18000") + "/api/auth/logout",
        {{ method: "POST", credentials: "include" }},
      );
    }} catch {{
      // ignore
    }}
    router.push("/login");
  }}

  return (
    <header className="flex h-14 items-center justify-between border-b px-6">
      <div className="lg:hidden text-lg font-semibold">{ir.marketplace.name}</div>
      <div className="flex items-center gap-2 ml-auto">
        <Button variant="ghost" size="sm" onClick={{handleLogout}}>
          Sign Out
        </Button>
      </div>
    </header>
  );
}}
"""


# ── Form components ───────────────────────────────────────────────────


def _field_renderer(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

import {{ Input }} from "@/components/ui/input";
import {{ Label }} from "@/components/ui/label";

interface FieldConfig {{
  name: string;
  label: string;
  type: string;
  required: boolean;
  options?: string[];
}}

interface FieldRendererProps {{
  field: FieldConfig;
  value: unknown;
  onChange: (name: string, value: unknown) => void;
}}

export function FieldRenderer({{ field, value, onChange }}: FieldRendererProps) {{
  const id = `field-${{field.name}}`;

  switch (field.type) {{
    case "text":
    case "rich_text":
    case "location":
      return (
        <div className="space-y-2">
          <Label htmlFor={{id}}>
            {{field.label}}
            {{field.required && <span className="text-destructive"> *</span>}}
          </Label>
          {{field.type === "rich_text" ? (
            <textarea
              id={{id}}
              className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm min-h-[100px]"
              value={{(value as string) ?? ""}}
              onChange={{(e) => onChange(field.name, e.target.value)}}
            />
          ) : (
            <Input
              id={{id}}
              value={{(value as string) ?? ""}}
              onChange={{(e) => onChange(field.name, e.target.value)}}
            />
          )}}
        </div>
      );

    case "number":
      return (
        <div className="space-y-2">
          <Label htmlFor={{id}}>
            {{field.label}}
            {{field.required && <span className="text-destructive"> *</span>}}
          </Label>
          <Input
            id={{id}}
            type="number"
            value={{value != null ? String(value) : ""}}
            onChange={{(e) => onChange(field.name, e.target.value ? Number(e.target.value) : undefined)}}
          />
        </div>
      );

    case "select":
      return (
        <div className="space-y-2">
          <Label htmlFor={{id}}>
            {{field.label}}
            {{field.required && <span className="text-destructive"> *</span>}}
          </Label>
          <select
            id={{id}}
            className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
            value={{(value as string) ?? ""}}
            onChange={{(e) => onChange(field.name, e.target.value)}}
          >
            <option value="">Select...</option>
            {{field.options?.map((opt) => (
              <option key={{opt}} value={{opt}}>
                {{opt}}
              </option>
            ))}}
          </select>
        </div>
      );

    case "multi_select":
      return (
        <div className="space-y-2">
          <Label>
            {{field.label}}
            {{field.required && <span className="text-destructive"> *</span>}}
          </Label>
          <div className="flex flex-wrap gap-2">
            {{field.options?.map((opt) => {{
              const selected = Array.isArray(value) && value.includes(opt);
              return (
                <button
                  key={{opt}}
                  type="button"
                  className={{`rounded-full border px-3 py-1 text-sm transition-colors ${{
                    selected
                      ? "border-primary bg-primary text-primary-foreground"
                      : "border-input hover:bg-accent"
                  }}`}}
                  onClick={{() => {{
                    const current = Array.isArray(value) ? value : [];
                    const next = selected
                      ? current.filter((v: string) => v !== opt)
                      : [...current, opt];
                    onChange(field.name, next);
                  }}}}
                >
                  {{opt}}
                </button>
              );
            }})}}
          </div>
        </div>
      );

    case "date":
      return (
        <div className="space-y-2">
          <Label htmlFor={{id}}>
            {{field.label}}
            {{field.required && <span className="text-destructive"> *</span>}}
          </Label>
          <Input
            id={{id}}
            type="date"
            value={{(value as string) ?? ""}}
            onChange={{(e) => onChange(field.name, e.target.value)}}
          />
        </div>
      );

    case "file":
    case "files":
      return (
        <div className="space-y-2">
          <Label htmlFor={{id}}>
            {{field.label}}
            {{field.required && <span className="text-destructive"> *</span>}}
          </Label>
          <Input
            id={{id}}
            type="file"
            multiple={{field.type === "files"}}
            onChange={{() => {{}}}}
          />
        </div>
      );

    default:
      return (
        <div className="space-y-2">
          <Label htmlFor={{id}}>{{field.label}}</Label>
          <Input
            id={{id}}
            value={{(value as string) ?? ""}}
            onChange={{(e) => onChange(field.name, e.target.value)}}
          />
        </div>
      );
  }}
}}
"""


def _profile_form(ir: FrontendIR) -> str:
    entity_branches = []
    for entity in ir.entities:
        sections_def = "[\n"
        for section in entity.sections:
            fields_arr = "[\n"
            for f in section.fields:
                opts = ""
                if f.options:
                    opts_str = ", ".join(f'"{o}"' for o in f.options)
                    opts = f", options: [{opts_str}]"
                fields_arr += (
                    f'          {{ name: "{f.name}", label: "{f.label}", '
                    f'type: "{f.field_type}", required: {str(f.required).lower()}'
                    f"{opts} }},\n"
                )
            fields_arr += "        ]"
            sections_def += (
                f'      {{ name: "{section.name}", fields: {fields_arr} }},\n'
            )
        sections_def += "    ]"

        entity_branches.append(
            f'    case "{entity.slug}":\n'
            f"      return {sections_def};"
        )

    switch_body = "\n".join(entity_branches)

    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

import {{ useState }} from "react";
import {{ Button }} from "@/components/ui/button";
import {{ Card, CardContent, CardHeader, CardTitle }} from "@/components/ui/card";
import {{ FieldRenderer }} from "./field-renderer";

interface SectionDef {{
  name: string;
  fields: {{
    name: string;
    label: string;
    type: string;
    required: boolean;
    options?: string[];
  }}[];
}}

function getSectionsForType(type: string): SectionDef[] {{
  switch (type) {{
{switch_body}
    default:
      return [];
  }}
}}

export function ProfileForm() {{
  const [participantType] = useState("{ir.entities[0].slug if ir.entities else ''}");
  const [fields, setFields] = useState<Record<string, unknown>>({{}});
  const [activeTab, setActiveTab] = useState(0);

  const sections = getSectionsForType(participantType);

  function handleFieldChange(name: string, value: unknown) {{
    setFields((prev) => ({{ ...prev, [name]: value }}));
  }}

  return (
    <div className="space-y-4">
      {{sections.length > 1 && (
        <div className="flex gap-2 border-b">
          {{sections.map((section, idx) => (
            <button
              key={{section.name}}
              type="button"
              className={{`px-4 py-2 text-sm font-medium transition-colors border-b-2 ${{
                idx === activeTab
                  ? "border-primary text-foreground"
                  : "border-transparent text-muted-foreground hover:text-foreground"
              }}`}}
              onClick={{() => setActiveTab(idx)}}
            >
              {{section.name}}
            </button>
          ))}}
        </div>
      )}}

      {{sections[activeTab] && (
        <Card>
          <CardHeader>
            <CardTitle>{{sections[activeTab].name}}</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {{sections[activeTab].fields.map((field) => (
              <FieldRenderer
                key={{field.name}}
                field={{field}}
                value={{fields[field.name]}}
                onChange={{handleFieldChange}}
              />
            ))}}
          </CardContent>
        </Card>
      )}}

      <div className="flex justify-end gap-2">
        <Button variant="outline">Save Draft</Button>
        <Button>Submit Profile</Button>
      </div>
    </div>
  );
}}
"""


# ── Shared components ─────────────────────────────────────────────────


def _search_filters(ir: FrontendIR) -> str:
    filter_buttons = ""
    for ff in ir.discovery.filter_fields:
        filter_buttons += f"""
        <button
          type="button"
          className="rounded-full border border-input px-3 py-1 text-sm hover:bg-accent"
        >
          {ff.replace("_", " ").title()}
        </button>"""

    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

export function SearchFilters() {{
  return (
    <div className="flex flex-wrap gap-2">
      <span className="text-sm font-medium text-muted-foreground py-1">Filters:</span>{filter_buttons}
    </div>
  );
}}
"""


def _profile_card(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
import Link from "next/link";
import {{ Card, CardContent, CardHeader, CardTitle }} from "@/components/ui/card";
import {{ Badge }} from "@/components/ui/badge";

interface ProfileCardProps {{
  id: string;
  name: string;
  type: string;
  fields: Record<string, unknown>;
}}

export function ProfileCard({{ id, name, type, fields }}: ProfileCardProps) {{
  return (
    <Link href={{`/profiles/${{id}}`}}>
      <Card className="transition-shadow hover:shadow-md">
        <CardHeader className="pb-2">
          <div className="flex items-center justify-between">
            <CardTitle className="text-lg">{{name}}</CardTitle>
            <Badge variant="secondary">{{type}}</Badge>
          </div>
        </CardHeader>
        <CardContent>
          <dl className="space-y-1 text-sm">
            {{Object.entries(fields)
              .slice(0, 3)
              .map(([key, val]) => (
                <div key={{key}} className="flex gap-2">
                  <dt className="font-medium text-muted-foreground">
                    {{key.replace(/_/g, " ")}}:
                  </dt>
                  <dd>{{Array.isArray(val) ? val.join(", ") : String(val ?? "—")}}</dd>
                </div>
              ))}}
          </dl>
        </CardContent>
      </Card>
    </Link>
  );
}}
"""


# ── shadcn/ui primitives ──────────────────────────────────────────────


def _shadcn_ui_components() -> dict[str, str]:
    """Emit minimal shadcn/ui component stubs.

    Full shadcn/ui components are large; we emit lean wrappers that
    follow the same API so ``npm run build`` succeeds.  Users can
    replace these with ``npx shadcn-ui@latest add <component>`` later.
    """
    files: dict[str, str] = {}

    files["src/components/ui/button.tsx"] = '''\
import * as React from "react";
import { Slot } from "@radix-ui/react-slot";
import { cn } from "@/lib/utils";

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: "default" | "destructive" | "outline" | "secondary" | "ghost" | "link";
  size?: "default" | "sm" | "lg" | "icon";
  asChild?: boolean;
}

const variantClasses: Record<string, string> = {
  default: "bg-primary text-primary-foreground hover:bg-primary/90",
  destructive: "bg-destructive text-destructive-foreground hover:bg-destructive/90",
  outline: "border border-input bg-background hover:bg-accent hover:text-accent-foreground",
  secondary: "bg-secondary text-secondary-foreground hover:bg-secondary/80",
  ghost: "hover:bg-accent hover:text-accent-foreground",
  link: "text-primary underline-offset-4 hover:underline",
};

const sizeClasses: Record<string, string> = {
  default: "h-10 px-4 py-2",
  sm: "h-9 rounded-md px-3",
  lg: "h-11 rounded-md px-8",
  icon: "h-10 w-10",
};

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant = "default", size = "default", asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : "button";
    return (
      <Comp
        className={cn(
          "inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50",
          variantClasses[variant],
          sizeClasses[size],
          className,
        )}
        ref={ref}
        {...props}
      />
    );
  },
);
Button.displayName = "Button";

export { Button };
'''

    files["src/components/ui/input.tsx"] = '''\
import * as React from "react";
import { cn } from "@/lib/utils";

export type InputProps = React.InputHTMLAttributes<HTMLInputElement>;

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className, type, ...props }, ref) => {
    return (
      <input
        type={type}
        className={cn(
          "flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50",
          className,
        )}
        ref={ref}
        {...props}
      />
    );
  },
);
Input.displayName = "Input";

export { Input };
'''

    files["src/components/ui/label.tsx"] = '''\
import * as React from "react";
import * as LabelPrimitive from "@radix-ui/react-label";
import { cn } from "@/lib/utils";

const Label = React.forwardRef<
  React.ElementRef<typeof LabelPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof LabelPrimitive.Root>
>(({ className, ...props }, ref) => (
  <LabelPrimitive.Root
    ref={ref}
    className={cn(
      "text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
      className,
    )}
    {...props}
  />
));
Label.displayName = LabelPrimitive.Root.displayName;

export { Label };
'''

    files["src/components/ui/card.tsx"] = '''\
import * as React from "react";
import { cn } from "@/lib/utils";

const Card = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn("rounded-lg border bg-card text-card-foreground shadow-sm", className)} {...props} />
  ),
);
Card.displayName = "Card";

const CardHeader = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn("flex flex-col space-y-1.5 p-6", className)} {...props} />
  ),
);
CardHeader.displayName = "CardHeader";

const CardTitle = React.forwardRef<HTMLParagraphElement, React.HTMLAttributes<HTMLHeadingElement>>(
  ({ className, ...props }, ref) => (
    <h3 ref={ref} className={cn("text-2xl font-semibold leading-none tracking-tight", className)} {...props} />
  ),
);
CardTitle.displayName = "CardTitle";

const CardDescription = React.forwardRef<HTMLParagraphElement, React.HTMLAttributes<HTMLParagraphElement>>(
  ({ className, ...props }, ref) => (
    <p ref={ref} className={cn("text-sm text-muted-foreground", className)} {...props} />
  ),
);
CardDescription.displayName = "CardDescription";

const CardContent = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn("p-6 pt-0", className)} {...props} />
  ),
);
CardContent.displayName = "CardContent";

const CardFooter = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn("flex items-center p-6 pt-0", className)} {...props} />
  ),
);
CardFooter.displayName = "CardFooter";

export { Card, CardHeader, CardFooter, CardTitle, CardDescription, CardContent };
'''

    files["src/components/ui/badge.tsx"] = '''\
import * as React from "react";
import { cn } from "@/lib/utils";

export interface BadgeProps extends React.HTMLAttributes<HTMLDivElement> {
  variant?: "default" | "secondary" | "destructive" | "outline";
}

const variantClasses: Record<string, string> = {
  default: "border-transparent bg-primary text-primary-foreground hover:bg-primary/80",
  secondary: "border-transparent bg-secondary text-secondary-foreground hover:bg-secondary/80",
  destructive: "border-transparent bg-destructive text-destructive-foreground hover:bg-destructive/80",
  outline: "text-foreground",
};

function Badge({ className, variant = "default", ...props }: BadgeProps) {
  return (
    <div
      className={cn(
        "inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2",
        variantClasses[variant],
        className,
      )}
      {...props}
    />
  );
}

export { Badge };
'''

    files["src/components/ui/separator.tsx"] = '''\
import * as React from "react";
import * as SeparatorPrimitive from "@radix-ui/react-separator";
import { cn } from "@/lib/utils";

const Separator = React.forwardRef<
  React.ElementRef<typeof SeparatorPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof SeparatorPrimitive.Root>
>(({ className, orientation = "horizontal", decorative = true, ...props }, ref) => (
  <SeparatorPrimitive.Root
    ref={ref}
    decorative={decorative}
    orientation={orientation}
    className={cn(
      "shrink-0 bg-border",
      orientation === "horizontal" ? "h-[1px] w-full" : "h-full w-[1px]",
      className,
    )}
    {...props}
  />
));
Separator.displayName = SeparatorPrimitive.Root.displayName;

export { Separator };
'''

    files["src/components/ui/skeleton.tsx"] = '''\
import { cn } from "@/lib/utils";

function Skeleton({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div className={cn("animate-pulse rounded-md bg-muted", className)} {...props} />
  );
}

export { Skeleton };
'''

    return files
