"""Generate React components from the FrontendIR.

Emits:
- Field renderer (maps IR field types to React components)
- Profile form (tabbed by section, wired to hooks)
- Sidebar layout
- Header
- Search filters
- Profile card
- shadcn/ui primitives
"""

from __future__ import annotations

from ..ir import FrontendIR

_HEADER = """\
// AUTO-GENERATED by Cosolvent Frontend Compiler v{version}
// spec_hash: {hash}
// DO NOT EDIT — changes will be overwritten on next compile
"""


def emit_components(ir: FrontendIR) -> dict[str, str]:
    files: dict[str, str] = {}

    # Layout components
    files["src/components/layouts/app-sidebar.tsx"] = _app_sidebar(ir)
    files["src/components/layouts/header.tsx"] = _header(ir)

    # Form components
    files["src/components/forms/field-renderer.tsx"] = _field_renderer(ir)
    files["src/components/forms/profile-form.tsx"] = _profile_form(ir)

    # Shared components
    files["src/components/shared/search-filters.tsx"] = _search_filters(ir)
    files["src/components/shared/profile-card.tsx"] = _profile_card(ir)

    # shadcn/ui primitives
    files.update(_shadcn_ui_components())

    return files


# ── Layout components ─────────────────────────────────────────────────


def _app_sidebar(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

import Link from "next/link";
import {{ usePathname }} from "next/navigation";
import {{ useEffect, useMemo, useState }} from "react";
import {{ useQuery }} from "@tanstack/react-query";
import {{ cn }} from "@/lib/utils";
import {{ navigationItems, marketplaceName, marketplaceLogo }} from "@/generated/navigation";
import * as notificationsApi from "@/generated/api/notifications";

interface NotificationLite {{
  is_read?: boolean;
}}

const NOTIFICATION_POLL_MS = 30_000;

export function AppSidebar() {{
  const pathname = usePathname();
  const [activeRole, setActiveRole] = useState<string | null>(null);

  useEffect(() => {{
    let cancelled = false;
    (async () => {{
      try {{
        const base = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:18000";
        const res = await fetch(`${{base}}/api/auth/me`, {{ credentials: "include" }});
        if (!res.ok) {{
          if (!cancelled) setActiveRole(null);
          return;
        }}
        const me = (await res.json()) as {{ role?: string; participant_type?: string }};
        const role = me.role === "admin" ? "admin" : (me.participant_type ?? null);
        if (!cancelled) setActiveRole(role);
      }} catch {{
        if (!cancelled) setActiveRole(null);
      }}
    }})();
    return () => {{
      cancelled = true;
    }};
  }}, []);

  // Poll the inbox for the unread count so the badge stays in sync without
  // requiring a websocket. Gated on ``activeRole`` so anonymous visitors
  // don't 401-spam the API. ``staleTime`` lines up with the poll interval to
  // keep tab focuses from triggering extra refetches.
  // Key starts with "notifications" so ``useMarkRead``'s ``invalidateQueries``
  // (which targets ``notificationsKeys.all`` = ``["notifications"]``) also
  // refreshes this sidebar query, keeping the badge in step with the inbox.
  const notifications = useQuery({{
    queryKey: ["notifications", "sidebar-badge"] as const,
    queryFn: () => notificationsApi.listNotifications(),
    enabled: Boolean(activeRole),
    refetchInterval: NOTIFICATION_POLL_MS,
    refetchIntervalInBackground: false,
    staleTime: NOTIFICATION_POLL_MS,
  }});
  const unreadCount = useMemo(() => {{
    const data = notifications.data;
    if (!Array.isArray(data)) return 0;
    return (data as NotificationLite[]).filter((n) => !n?.is_read).length;
  }}, [notifications.data]);

  const visibleItems = useMemo(
    () =>
      navigationItems.filter((item) => {{
        if (!item.roles?.length) return true;
        if (activeRole) return item.roles.includes(activeRole);
        // Unknown role (or logged out): hide admin-only links.
        return !item.roles.includes("admin");
      }}),
    [activeRole],
  );

  return (
    <aside className="hidden w-64 shrink-0 border-r bg-sidebar lg:block">
      <div className="flex h-14 items-center border-b px-4">
        <Link
          href="/"
          className="flex items-center gap-2 text-lg font-semibold tracking-tight text-sidebar-foreground"
        >
          {{marketplaceLogo && (
            <span aria-hidden className="text-xl leading-none">{{marketplaceLogo}}</span>
          )}}
          <span>{{marketplaceName}}</span>
        </Link>
      </div>
      {{/* AGENT_FILL:sidebar_nav:start */}}
      <nav className="space-y-1 p-3">
        {{visibleItems.map((item) => {{
          const Icon = item.icon;
          const isActive =
            pathname === item.route ||
            (item.route !== "/" && pathname.startsWith(item.route));
          const badge =
            item.route === "/notifications" && unreadCount > 0
              ? unreadCount
              : 0;
          return (
            <Link
              key={{`${{item.route}}:${{item.label}}`}}
              href={{item.route}}
              className={{cn(
                "flex items-center gap-3 rounded-md px-3 py-2 text-sm font-medium transition-colors",
                isActive
                  ? "bg-sidebar-accent text-sidebar-accent-foreground"
                  : "text-sidebar-foreground hover:bg-sidebar-accent/50",
              )}}
            >
              <Icon className="h-4 w-4" />
              <span className="flex-1">{{item.label}}</span>
              {{badge > 0 && (
                <span
                  aria-label={{`${{badge}} unread`}}
                  className="inline-flex min-w-[1.25rem] items-center justify-center rounded-full bg-destructive px-1.5 py-0.5 text-[10px] font-semibold leading-none text-destructive-foreground"
                >
                  {{badge > 99 ? "99+" : badge}}
                </span>
              )}}
            </Link>
          );
        }})}}
      </nav>
      {{/* AGENT_FILL:sidebar_nav:end */}}
    </aside>
  );
}}
"""


def _header(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

import {{ useRouter }} from "next/navigation";
import {{ Button }} from "@/components/ui/button";

export function Header() {{
  const router = useRouter();

  async function handleLogout() {{
    try {{
      await fetch(
        (process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:18000") + "/api/auth/logout",
        {{ method: "POST", credentials: "include" }},
      );
    }} catch {{
      // ignore
    }}
    router.push("/login");
  }}

  return (
    <>
      {{/* AGENT_FILL:app_header:start */}}
      <header className="flex h-14 items-center justify-between border-b px-6">
        <div className="lg:hidden text-lg font-semibold">{ir.marketplace.name}</div>
        <div className="flex items-center gap-2 ml-auto">
          <Button variant="ghost" size="sm" onClick={{handleLogout}}>
            Sign Out
          </Button>
        </div>
      </header>
      {{/* AGENT_FILL:app_header:end */}}
    </>
  );
}}
"""


# ── Form components ───────────────────────────────────────────────────


def _field_renderer(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

import {{ Input }} from "@/components/ui/input";
import {{ Label }} from "@/components/ui/label";

interface FieldConfig {{
  name: string;
  label: string;
  type: string;
  required: boolean;
  options?: string[];
}}

interface FieldRendererProps {{
  field: FieldConfig;
  value: unknown;
  onChange: (name: string, value: unknown) => void;
}}

export function FieldRenderer({{ field, value, onChange }}: FieldRendererProps) {{
  const id = `field-${{field.name}}`;

  switch (field.type) {{
    case "text":
    case "rich_text":
    case "location":
      return (
        <div className="space-y-2">
          <Label htmlFor={{id}}>
            {{field.label}}
            {{field.required && <span className="text-destructive"> *</span>}}
          </Label>
          {{field.type === "rich_text" ? (
            <textarea
              id={{id}}
              className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm min-h-[100px]"
              value={{(value as string) ?? ""}}
              onChange={{(e) => onChange(field.name, e.target.value)}}
            />
          ) : (
            <Input
              id={{id}}
              value={{(value as string) ?? ""}}
              onChange={{(e) => onChange(field.name, e.target.value)}}
            />
          )}}
        </div>
      );

    case "number":
      return (
        <div className="space-y-2">
          <Label htmlFor={{id}}>
            {{field.label}}
            {{field.required && <span className="text-destructive"> *</span>}}
          </Label>
          <Input
            id={{id}}
            type="number"
            value={{value != null ? String(value) : ""}}
            onChange={{(e) => onChange(field.name, e.target.value ? Number(e.target.value) : undefined)}}
          />
        </div>
      );

    case "select":
      return (
        <div className="space-y-2">
          <Label htmlFor={{id}}>
            {{field.label}}
            {{field.required && <span className="text-destructive"> *</span>}}
          </Label>
          <select
            id={{id}}
            className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
            value={{(value as string) ?? ""}}
            onChange={{(e) => onChange(field.name, e.target.value)}}
          >
            <option value="">Select...</option>
            {{field.options?.map((opt) => (
              <option key={{opt}} value={{opt}}>
                {{opt}}
              </option>
            ))}}
          </select>
        </div>
      );

    case "multi_select":
      return (
        <div className="space-y-2">
          <Label>
            {{field.label}}
            {{field.required && <span className="text-destructive"> *</span>}}
          </Label>
          <div className="flex flex-wrap gap-2">
            {{field.options?.map((opt) => {{
              const selected = Array.isArray(value) && value.includes(opt);
              return (
                <button
                  key={{opt}}
                  type="button"
                  className={{`rounded-full border px-3 py-1 text-sm transition-colors ${{
                    selected
                      ? "border-primary bg-primary text-primary-foreground"
                      : "border-input hover:bg-accent"
                  }}`}}
                  onClick={{() => {{
                    const current = Array.isArray(value) ? value : [];
                    const next = selected
                      ? current.filter((v: string) => v !== opt)
                      : [...current, opt];
                    onChange(field.name, next);
                  }}}}
                >
                  {{opt}}
                </button>
              );
            }})}}
          </div>
        </div>
      );

    case "date":
      return (
        <div className="space-y-2">
          <Label htmlFor={{id}}>
            {{field.label}}
            {{field.required && <span className="text-destructive"> *</span>}}
          </Label>
          <Input
            id={{id}}
            type="date"
            value={{(value as string) ?? ""}}
            onChange={{(e) => onChange(field.name, e.target.value)}}
          />
        </div>
      );

    case "file":
    case "files": {{
      const isMulti = field.type === "files";
      const fileValue = value as File | File[] | null | undefined;
      const fileList: File[] = Array.isArray(fileValue)
        ? fileValue
        : fileValue instanceof File
        ? [fileValue]
        : [];

      // Multi-file fields ACCUMULATE picks: each new selection is merged with
      // existing files (deduped by name+size+lastModified). The native
      // ``<input type=file multiple>`` replaces selection on each open, which
      // surprises users who pick a few files now and want to add more later.
      // Single-file fields keep replace semantics.
      function handleFilePick(e: React.ChangeEvent<HTMLInputElement>) {{
        const picked = e.target.files ? Array.from(e.target.files) : [];
        if (!isMulti) {{
          onChange(field.name, picked[0] ?? null);
          e.target.value = "";
          return;
        }}
        const dedupKey = (f: File) => `${{f.name}}|${{f.size}}|${{f.lastModified}}`;
        const seen = new Set(fileList.map(dedupKey));
        const merged = [...fileList];
        for (const f of picked) {{
          if (!seen.has(dedupKey(f))) merged.push(f);
        }}
        onChange(field.name, merged);
        // Reset the picker so re-selecting the same file fires onChange again.
        e.target.value = "";
      }}

      function removeAt(idx: number) {{
        if (!isMulti) {{
          onChange(field.name, null);
          return;
        }}
        const next = fileList.filter((_, i) => i !== idx);
        onChange(field.name, next);
      }}

      return (
        <div className="space-y-2">
          <Label htmlFor={{id}}>
            {{field.label}}
            {{field.required && <span className="text-destructive"> *</span>}}
          </Label>
          <Input
            id={{id}}
            type="file"
            multiple={{isMulti}}
            onChange={{handleFilePick}}
          />
          {{fileList.length > 0 && (
            <ul className="space-y-1 rounded-md border bg-muted/30 p-2 text-xs">
              {{fileList.map((f, idx) => (
                <li
                  key={{`${{f.name}}-${{f.size}}-${{idx}}`}}
                  className="flex items-center justify-between gap-2"
                >
                  <span className="flex-1 truncate text-muted-foreground">
                    📎 {{f.name}}
                  </span>
                  <span className="shrink-0 text-muted-foreground">
                    {{Math.round(f.size / 1024)}} KB
                  </span>
                  <button
                    type="button"
                    onClick={{() => removeAt(idx)}}
                    className="shrink-0 rounded px-1.5 text-muted-foreground hover:bg-destructive/10 hover:text-destructive"
                    aria-label={{`Remove ${{f.name}}`}}
                  >
                    ✕
                  </button>
                </li>
              ))}}
            </ul>
          )}}
        </div>
      );
    }}

    default:
      return (
        <div className="space-y-2">
          <Label htmlFor={{id}}>{{field.label}}</Label>
          <Input
            id={{id}}
            value={{(value as string) ?? ""}}
            onChange={{(e) => onChange(field.name, e.target.value)}}
          />
        </div>
      );
  }}
}}
"""


def _profile_form(ir: FrontendIR) -> str:
    entity_branches = []
    for entity in ir.entities:
        sections_def = "[\n"
        for section in entity.sections:
            fields_arr = "[\n"
            for f in section.fields:
                opts = ""
                if f.options:
                    opts_str = ", ".join(f'"{o}"' for o in f.options)
                    opts = f", options: [{opts_str}]"
                fields_arr += (
                    f'          {{ name: "{f.name}", label: "{f.label}", '
                    f'type: "{f.field_type}", required: {str(f.required).lower()}'
                    f"{opts} }},\n"
                )
            fields_arr += "        ]"
            sections_def += (
                f'      {{ name: "{section.name}", fields: {fields_arr} }},\n'
            )
        sections_def += "    ]"

        entity_branches.append(
            f'    case "{entity.slug}":\n'
            f"      return {sections_def};"
        )

    switch_body = "\n".join(entity_branches)

    default_slug = ir.entities[0].slug if ir.entities else ""
    role_options = "".join(
        f'    <option key="{e.slug}" value="{e.slug}">{e.name}</option>\n'
        for e in ir.entities
    )

    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

import {{ useEffect, useMemo, useState }} from "react";
import {{ useRouter }} from "next/navigation";
import {{ Button }} from "@/components/ui/button";
import {{ Card, CardContent, CardHeader, CardTitle }} from "@/components/ui/card";
import {{ FieldRenderer }} from "./field-renderer";
import {{ useAuth }} from "@/generated/hooks/use-current-user";
import {{ useDraft, useUpdateDraft, useRegister }} from "@/generated/hooks/use-profiles";

interface SectionDef {{
  name: string;
  fields: {{
    name: string;
    label: string;
    type: string;
    required: boolean;
    options?: string[];
  }}[];
}}

function getSectionsForType(type: string): SectionDef[] {{
  switch (type) {{
{switch_body}
    default:
      return [];
  }}
}}

interface DraftLike {{
  fields?: Record<string, unknown>;
  status?: string;
}}

export function ProfileForm() {{
  const router = useRouter();
  const {{ user }} = useAuth();

  const initialType = user?.participant_type ?? "{default_slug}";
  const [participantType, setParticipantType] = useState(initialType);
  const [fields, setFields] = useState<Record<string, unknown>>({{}});
  const [activeTab, setActiveTab] = useState(0);
  const [feedback, setFeedback] = useState<{{ kind: "ok" | "err"; text: string }} | null>(null);

  useEffect(() => {{
    if (user?.participant_type && user.participant_type !== participantType) {{
      setParticipantType(user.participant_type);
    }}
  }}, [user?.participant_type, participantType]);

  const draftQuery = useDraft(participantType);
  const updateDraft = useUpdateDraft();
  const registerProfile = useRegister();

  useEffect(() => {{
    const data = draftQuery.data as DraftLike | undefined;
    if (data?.fields) {{
      setFields(data.fields);
    }}
  }}, [draftQuery.data]);

  const sections = useMemo(
    () => getSectionsForType(participantType),
    [participantType],
  );

  function handleFieldChange(name: string, value: unknown) {{
    setFields((prev) => ({{ ...prev, [name]: value }}));
  }}

  async function handleSaveDraft() {{
    if (!participantType) return;
    setFeedback(null);
    try {{
      await updateDraft.mutateAsync({{
        type_slug: participantType,
        body: {{ fields }},
      }} as Parameters<typeof updateDraft.mutateAsync>[0]);
      setFeedback({{ kind: "ok", text: "Draft saved." }});
    }} catch (err: unknown) {{
      setFeedback({{
        kind: "err",
        text: err instanceof Error ? err.message : "Failed to save draft",
      }});
    }}
  }}

  async function handleSubmitProfile() {{
    if (!participantType) return;
    setFeedback(null);
    try {{
      await updateDraft.mutateAsync({{
        type_slug: participantType,
        body: {{ fields }},
      }} as Parameters<typeof updateDraft.mutateAsync>[0]);
      await registerProfile.mutateAsync(
        participantType as Parameters<typeof registerProfile.mutateAsync>[0],
      );
      setFeedback({{ kind: "ok", text: "Profile submitted." }});
      router.push("/profile");
    }} catch (err: unknown) {{
      setFeedback({{
        kind: "err",
        text: err instanceof Error ? err.message : "Failed to submit profile",
      }});
    }}
  }}

  const draftStatus = (draftQuery.data as DraftLike | undefined)?.status;

  return (
    <>
      {{/* AGENT_FILL:profile_form:start */}}
      <div className="space-y-4">
        {{!user?.participant_type && (
          <Card>
            <CardHeader>
              <CardTitle>Choose your role</CardTitle>
            </CardHeader>
            <CardContent>
              <select
                className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                value={{participantType}}
                onChange={{(e) => {{
                  setParticipantType(e.target.value);
                  setFields({{}});
                  setActiveTab(0);
                }}}}
              >
{role_options}              </select>
            </CardContent>
          </Card>
        )}}

        {{draftStatus && (
          <p className="text-xs text-muted-foreground">
            Draft status: <span className="font-medium capitalize">{{draftStatus}}</span>
          </p>
        )}}

        {{sections.length > 1 && (
          <div className="flex gap-2 border-b">
            {{sections.map((section, idx) => (
              <button
                key={{section.name}}
                type="button"
                className={{`px-4 py-2 text-sm font-medium transition-colors border-b-2 ${{
                  idx === activeTab
                    ? "border-primary text-foreground"
                    : "border-transparent text-muted-foreground hover:text-foreground"
                }}`}}
                onClick={{() => setActiveTab(idx)}}
              >
                {{section.name}}
              </button>
            ))}}
          </div>
        )}}

        {{sections[activeTab] && (
          <Card>
            <CardHeader>
              <CardTitle>{{sections[activeTab].name}}</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {{draftQuery.isLoading ? (
                <p className="text-sm text-muted-foreground">Loading draft…</p>
              ) : (
                sections[activeTab].fields.map((field) => (
                  <FieldRenderer
                    key={{field.name}}
                    field={{field}}
                    value={{fields[field.name]}}
                    onChange={{handleFieldChange}}
                  />
                ))
              )}}
            </CardContent>
          </Card>
        )}}

        {{feedback && (
          <p
            className={{
              feedback.kind === "ok"
                ? "text-sm text-emerald-600"
                : "text-sm text-destructive"
            }}
          >
            {{feedback.text}}
          </p>
        )}}

        <div className="flex justify-end gap-2">
          <Button
            variant="outline"
            type="button"
            disabled={{updateDraft.isPending}}
            onClick={{() => void handleSaveDraft()}}
          >
            {{updateDraft.isPending ? "Saving…" : "Save Draft"}}
          </Button>
          <Button
            type="button"
            disabled={{updateDraft.isPending || registerProfile.isPending}}
            onClick={{() => void handleSubmitProfile()}}
          >
            {{registerProfile.isPending ? "Submitting…" : "Submit Profile"}}
          </Button>
        </div>
      </div>
      {{/* AGENT_FILL:profile_form:end */}}
    </>
  );
}}
"""


# ── Shared components ─────────────────────────────────────────────────


def _search_filters(ir: FrontendIR) -> str:
    filter_buttons = ""
    for ff in ir.discovery.filter_fields:
        filter_buttons += f"""
        <button
          type="button"
          className="rounded-full border border-input px-3 py-1 text-sm hover:bg-accent"
        >
          {ff.replace("_", " ").title()}
        </button>"""

    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

export function SearchFilters() {{
  return (
    <div className="flex flex-wrap gap-2">
      <span className="text-sm font-medium text-muted-foreground py-1">Filters:</span>{filter_buttons}
    </div>
  );
}}
"""


def _profile_card(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
import Link from "next/link";
import {{ Card, CardContent, CardHeader, CardTitle }} from "@/components/ui/card";
import {{ Badge }} from "@/components/ui/badge";

interface ProfileCardProps {{
  id: string;
  name: string;
  type: string;
  fields: Record<string, unknown>;
}}

export function ProfileCard({{ id, name, type, fields }}: ProfileCardProps) {{
  return (
    <Link href={{`/profiles/${{encodeURIComponent(type)}}/${{encodeURIComponent(id)}}`}}>
      <Card className="transition-shadow hover:shadow-md">
        <CardHeader className="pb-2">
          <div className="flex items-center justify-between">
            <CardTitle className="text-lg">{{name}}</CardTitle>
            <Badge variant="secondary">{{type}}</Badge>
          </div>
        </CardHeader>
        <CardContent>
          <dl className="space-y-1 text-sm">
            {{Object.entries(fields)
              .slice(0, 3)
              .map(([key, val]) => (
                <div key={{key}} className="flex gap-2">
                  <dt className="font-medium text-muted-foreground">
                    {{key.replace(/_/g, " ")}}:
                  </dt>
                  <dd>{{Array.isArray(val) ? val.join(", ") : String(val ?? "—")}}</dd>
                </div>
              ))}}
          </dl>
        </CardContent>
      </Card>
    </Link>
  );
}}
"""


# ── shadcn/ui primitives ──────────────────────────────────────────────


def _shadcn_ui_components() -> dict[str, str]:
    """Emit a baseline shadcn/ui component set used by generated pages."""
    files: dict[str, str] = {}

    files["src/components/ui/button.tsx"] = '''\
import * as React from "react";
import { Slot } from "@radix-ui/react-slot";
import { cn } from "@/lib/utils";

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: "default" | "destructive" | "outline" | "secondary" | "ghost" | "link";
  size?: "default" | "sm" | "lg" | "icon";
  asChild?: boolean;
}

const variantClasses: Record<string, string> = {
  default: "bg-primary text-primary-foreground hover:bg-primary/90",
  destructive: "bg-destructive text-destructive-foreground hover:bg-destructive/90",
  outline: "border border-input bg-background hover:bg-accent hover:text-accent-foreground",
  secondary: "bg-secondary text-secondary-foreground hover:bg-secondary/80",
  ghost: "hover:bg-accent hover:text-accent-foreground",
  link: "text-primary underline-offset-4 hover:underline",
};

const sizeClasses: Record<string, string> = {
  default: "h-10 px-4 py-2",
  sm: "h-9 rounded-md px-3",
  lg: "h-11 rounded-md px-8",
  icon: "h-10 w-10",
};

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant = "default", size = "default", asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : "button";
    return (
      <Comp
        className={cn(
          "inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50",
          variantClasses[variant],
          sizeClasses[size],
          className,
        )}
        ref={ref}
        {...props}
      />
    );
  },
);
Button.displayName = "Button";

export { Button };
'''

    files["src/components/ui/input.tsx"] = '''\
import * as React from "react";
import { cn } from "@/lib/utils";

export type InputProps = React.InputHTMLAttributes<HTMLInputElement>;

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className, type, ...props }, ref) => {
    return (
      <input
        type={type}
        className={cn(
          "flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50",
          className,
        )}
        ref={ref}
        {...props}
      />
    );
  },
);
Input.displayName = "Input";

export { Input };
'''

    files["src/components/ui/label.tsx"] = '''\
import * as React from "react";
import * as LabelPrimitive from "@radix-ui/react-label";
import { cn } from "@/lib/utils";

const Label = React.forwardRef<
  React.ElementRef<typeof LabelPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof LabelPrimitive.Root>
>(({ className, ...props }, ref) => (
  <LabelPrimitive.Root
    ref={ref}
    className={cn(
      "text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
      className,
    )}
    {...props}
  />
));
Label.displayName = LabelPrimitive.Root.displayName;

export { Label };
'''

    files["src/components/ui/card.tsx"] = '''\
import * as React from "react";
import { cn } from "@/lib/utils";

const Card = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn("rounded-lg border bg-card text-card-foreground shadow-sm", className)} {...props} />
  ),
);
Card.displayName = "Card";

const CardHeader = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn("flex flex-col space-y-1.5 p-6", className)} {...props} />
  ),
);
CardHeader.displayName = "CardHeader";

const CardTitle = React.forwardRef<HTMLParagraphElement, React.HTMLAttributes<HTMLHeadingElement>>(
  ({ className, ...props }, ref) => (
    <h3 ref={ref} className={cn("text-2xl font-semibold leading-none tracking-tight", className)} {...props} />
  ),
);
CardTitle.displayName = "CardTitle";

const CardDescription = React.forwardRef<HTMLParagraphElement, React.HTMLAttributes<HTMLParagraphElement>>(
  ({ className, ...props }, ref) => (
    <p ref={ref} className={cn("text-sm text-muted-foreground", className)} {...props} />
  ),
);
CardDescription.displayName = "CardDescription";

const CardContent = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn("p-6 pt-0", className)} {...props} />
  ),
);
CardContent.displayName = "CardContent";

const CardFooter = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn("flex items-center p-6 pt-0", className)} {...props} />
  ),
);
CardFooter.displayName = "CardFooter";

export { Card, CardHeader, CardFooter, CardTitle, CardDescription, CardContent };
'''

    files["src/components/ui/badge.tsx"] = '''\
import * as React from "react";
import { cn } from "@/lib/utils";

export interface BadgeProps extends React.HTMLAttributes<HTMLDivElement> {
  variant?: "default" | "secondary" | "destructive" | "outline";
}

const variantClasses: Record<string, string> = {
  default: "border-transparent bg-primary text-primary-foreground hover:bg-primary/80",
  secondary: "border-transparent bg-secondary text-secondary-foreground hover:bg-secondary/80",
  destructive: "border-transparent bg-destructive text-destructive-foreground hover:bg-destructive/80",
  outline: "text-foreground",
};

function Badge({ className, variant = "default", ...props }: BadgeProps) {
  return (
    <div
      className={cn(
        "inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2",
        variantClasses[variant],
        className,
      )}
      {...props}
    />
  );
}

export { Badge };
'''

    files["src/components/ui/separator.tsx"] = '''\
import * as React from "react";
import * as SeparatorPrimitive from "@radix-ui/react-separator";
import { cn } from "@/lib/utils";

const Separator = React.forwardRef<
  React.ElementRef<typeof SeparatorPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof SeparatorPrimitive.Root>
>(({ className, orientation = "horizontal", decorative = true, ...props }, ref) => (
  <SeparatorPrimitive.Root
    ref={ref}
    decorative={decorative}
    orientation={orientation}
    className={cn(
      "shrink-0 bg-border",
      orientation === "horizontal" ? "h-[1px] w-full" : "h-full w-[1px]",
      className,
    )}
    {...props}
  />
));
Separator.displayName = SeparatorPrimitive.Root.displayName;

export { Separator };
'''

    files["src/components/ui/skeleton.tsx"] = '''\
import { cn } from "@/lib/utils";

function Skeleton({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div className={cn("animate-pulse rounded-md bg-muted", className)} {...props} />
  );
}

export { Skeleton };
'''

    files["src/components/ui/table.tsx"] = '''\
import * as React from "react";
import { cn } from "@/lib/utils";

const Table = React.forwardRef<HTMLTableElement, React.HTMLAttributes<HTMLTableElement>>(
  ({ className, ...props }, ref) => (
    <div className="relative w-full overflow-auto">
      <table ref={ref} className={cn("w-full caption-bottom text-sm", className)} {...props} />
    </div>
  ),
);
Table.displayName = "Table";

const TableHeader = React.forwardRef<HTMLTableSectionElement, React.HTMLAttributes<HTMLTableSectionElement>>(
  ({ className, ...props }, ref) => (
    <thead ref={ref} className={cn("[&_tr]:border-b", className)} {...props} />
  ),
);
TableHeader.displayName = "TableHeader";

const TableBody = React.forwardRef<HTMLTableSectionElement, React.HTMLAttributes<HTMLTableSectionElement>>(
  ({ className, ...props }, ref) => (
    <tbody ref={ref} className={cn("[&_tr:last-child]:border-0", className)} {...props} />
  ),
);
TableBody.displayName = "TableBody";

const TableFooter = React.forwardRef<HTMLTableSectionElement, React.HTMLAttributes<HTMLTableSectionElement>>(
  ({ className, ...props }, ref) => (
    <tfoot ref={ref} className={cn("border-t bg-muted/50 font-medium [&>tr]:last:border-b-0", className)} {...props} />
  ),
);
TableFooter.displayName = "TableFooter";

const TableRow = React.forwardRef<HTMLTableRowElement, React.HTMLAttributes<HTMLTableRowElement>>(
  ({ className, ...props }, ref) => (
    <tr ref={ref} className={cn("border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted", className)} {...props} />
  ),
);
TableRow.displayName = "TableRow";

const TableHead = React.forwardRef<HTMLTableCellElement, React.ThHTMLAttributes<HTMLTableCellElement>>(
  ({ className, ...props }, ref) => (
    <th ref={ref} className={cn("h-10 px-2 text-left align-middle font-medium text-muted-foreground", className)} {...props} />
  ),
);
TableHead.displayName = "TableHead";

const TableCell = React.forwardRef<HTMLTableCellElement, React.TdHTMLAttributes<HTMLTableCellElement>>(
  ({ className, ...props }, ref) => (
    <td ref={ref} className={cn("p-2 align-middle", className)} {...props} />
  ),
);
TableCell.displayName = "TableCell";

const TableCaption = React.forwardRef<HTMLTableCaptionElement, React.HTMLAttributes<HTMLTableCaptionElement>>(
  ({ className, ...props }, ref) => (
    <caption ref={ref} className={cn("mt-4 text-sm text-muted-foreground", className)} {...props} />
  ),
);
TableCaption.displayName = "TableCaption";

export {
  Table,
  TableHeader,
  TableBody,
  TableFooter,
  TableHead,
  TableRow,
  TableCell,
  TableCaption,
};
'''

    files["src/components/ui/tabs.tsx"] = '''\
import * as React from "react";
import * as TabsPrimitive from "@radix-ui/react-tabs";
import { cn } from "@/lib/utils";

const Tabs = TabsPrimitive.Root;

const TabsList = React.forwardRef<
  React.ElementRef<typeof TabsPrimitive.List>,
  React.ComponentPropsWithoutRef<typeof TabsPrimitive.List>
>(({ className, ...props }, ref) => (
  <TabsPrimitive.List
    ref={ref}
    className={cn("inline-flex h-10 items-center justify-center rounded-md bg-muted p-1 text-muted-foreground", className)}
    {...props}
  />
));
TabsList.displayName = TabsPrimitive.List.displayName;

const TabsTrigger = React.forwardRef<
  React.ElementRef<typeof TabsPrimitive.Trigger>,
  React.ComponentPropsWithoutRef<typeof TabsPrimitive.Trigger>
>(({ className, ...props }, ref) => (
  <TabsPrimitive.Trigger
    ref={ref}
    className={cn(
      "inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-sm",
      className,
    )}
    {...props}
  />
));
TabsTrigger.displayName = TabsPrimitive.Trigger.displayName;

const TabsContent = React.forwardRef<
  React.ElementRef<typeof TabsPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof TabsPrimitive.Content>
>(({ className, ...props }, ref) => (
  <TabsPrimitive.Content
    ref={ref}
    className={cn("mt-2 ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2", className)}
    {...props}
  />
));
TabsContent.displayName = TabsPrimitive.Content.displayName;

export { Tabs, TabsList, TabsTrigger, TabsContent };
'''

    files["src/components/ui/avatar.tsx"] = '''\
import * as React from "react";
import * as AvatarPrimitive from "@radix-ui/react-avatar";
import { cn } from "@/lib/utils";

const Avatar = React.forwardRef<
  React.ElementRef<typeof AvatarPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof AvatarPrimitive.Root>
>(({ className, ...props }, ref) => (
  <AvatarPrimitive.Root ref={ref} className={cn("relative flex h-10 w-10 shrink-0 overflow-hidden rounded-full", className)} {...props} />
));
Avatar.displayName = AvatarPrimitive.Root.displayName;

const AvatarImage = React.forwardRef<
  React.ElementRef<typeof AvatarPrimitive.Image>,
  React.ComponentPropsWithoutRef<typeof AvatarPrimitive.Image>
>(({ className, ...props }, ref) => (
  <AvatarPrimitive.Image ref={ref} className={cn("aspect-square h-full w-full", className)} {...props} />
));
AvatarImage.displayName = AvatarPrimitive.Image.displayName;

const AvatarFallback = React.forwardRef<
  React.ElementRef<typeof AvatarPrimitive.Fallback>,
  React.ComponentPropsWithoutRef<typeof AvatarPrimitive.Fallback>
>(({ className, ...props }, ref) => (
  <AvatarPrimitive.Fallback ref={ref} className={cn("flex h-full w-full items-center justify-center rounded-full bg-muted", className)} {...props} />
));
AvatarFallback.displayName = AvatarPrimitive.Fallback.displayName;

export { Avatar, AvatarImage, AvatarFallback };
'''

    files["src/components/ui/select.tsx"] = '''\
import * as React from "react";
import * as SelectPrimitive from "@radix-ui/react-select";
import { cn } from "@/lib/utils";

const Select = SelectPrimitive.Root;
const SelectGroup = SelectPrimitive.Group;
const SelectValue = SelectPrimitive.Value;

const SelectTrigger = React.forwardRef<
  React.ElementRef<typeof SelectPrimitive.Trigger>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.Trigger>
>(({ className, children, ...props }, ref) => (
  <SelectPrimitive.Trigger
    ref={ref}
    className={cn("flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50", className)}
    {...props}
  >
    {children}
  </SelectPrimitive.Trigger>
));
SelectTrigger.displayName = SelectPrimitive.Trigger.displayName;

const SelectContent = React.forwardRef<
  React.ElementRef<typeof SelectPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.Content>
>(({ className, children, ...props }, ref) => (
  <SelectPrimitive.Portal>
    <SelectPrimitive.Content
      ref={ref}
      className={cn("relative z-50 max-h-96 min-w-[8rem] overflow-hidden rounded-md border bg-popover text-popover-foreground shadow-md", className)}
      {...props}
    >
      <SelectPrimitive.Viewport className="p-1">{children}</SelectPrimitive.Viewport>
    </SelectPrimitive.Content>
  </SelectPrimitive.Portal>
));
SelectContent.displayName = SelectPrimitive.Content.displayName;

const SelectLabel = React.forwardRef<
  React.ElementRef<typeof SelectPrimitive.Label>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.Label>
>(({ className, ...props }, ref) => (
  <SelectPrimitive.Label ref={ref} className={cn("py-1.5 pl-8 pr-2 text-sm font-semibold", className)} {...props} />
));
SelectLabel.displayName = SelectPrimitive.Label.displayName;

const SelectItem = React.forwardRef<
  React.ElementRef<typeof SelectPrimitive.Item>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.Item>
>(({ className, children, ...props }, ref) => (
  <SelectPrimitive.Item
    ref={ref}
    className={cn("relative flex w-full cursor-default select-none items-center rounded-sm py-1.5 pl-8 pr-2 text-sm outline-none focus:bg-accent focus:text-accent-foreground", className)}
    {...props}
  >
    <SelectPrimitive.ItemText>{children}</SelectPrimitive.ItemText>
  </SelectPrimitive.Item>
));
SelectItem.displayName = SelectPrimitive.Item.displayName;

const SelectSeparator = React.forwardRef<
  React.ElementRef<typeof SelectPrimitive.Separator>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.Separator>
>(({ className, ...props }, ref) => (
  <SelectPrimitive.Separator ref={ref} className={cn("-mx-1 my-1 h-px bg-muted", className)} {...props} />
));
SelectSeparator.displayName = SelectPrimitive.Separator.displayName;

export {
  Select,
  SelectGroup,
  SelectValue,
  SelectTrigger,
  SelectContent,
  SelectLabel,
  SelectItem,
  SelectSeparator,
};
'''

    files["src/components/ui/dialog.tsx"] = '''\
import * as React from "react";
import * as DialogPrimitive from "@radix-ui/react-dialog";
import { cn } from "@/lib/utils";

const Dialog = DialogPrimitive.Root;
const DialogTrigger = DialogPrimitive.Trigger;
const DialogPortal = DialogPrimitive.Portal;
const DialogClose = DialogPrimitive.Close;

const DialogOverlay = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Overlay>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitive.Overlay>
>(({ className, ...props }, ref) => (
  <DialogPrimitive.Overlay
    ref={ref}
    className={cn("fixed inset-0 z-50 bg-black/80", className)}
    {...props}
  />
));
DialogOverlay.displayName = DialogPrimitive.Overlay.displayName;

const DialogContent = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitive.Content>
>(({ className, ...props }, ref) => (
  <DialogPortal>
    <DialogOverlay />
    <DialogPrimitive.Content
      ref={ref}
      className={cn("fixed left-[50%] top-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 rounded-lg border bg-background p-6 shadow-lg", className)}
      {...props}
    />
  </DialogPortal>
));
DialogContent.displayName = DialogPrimitive.Content.displayName;

const DialogHeader = ({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) => (
  <div className={cn("flex flex-col space-y-1.5 text-center sm:text-left", className)} {...props} />
);

const DialogFooter = ({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) => (
  <div className={cn("flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2", className)} {...props} />
);

const DialogTitle = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Title>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitive.Title>
>(({ className, ...props }, ref) => (
  <DialogPrimitive.Title ref={ref} className={cn("text-lg font-semibold leading-none tracking-tight", className)} {...props} />
));
DialogTitle.displayName = DialogPrimitive.Title.displayName;

const DialogDescription = React.forwardRef<
  React.ElementRef<typeof DialogPrimitive.Description>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitive.Description>
>(({ className, ...props }, ref) => (
  <DialogPrimitive.Description ref={ref} className={cn("text-sm text-muted-foreground", className)} {...props} />
));
DialogDescription.displayName = DialogPrimitive.Description.displayName;

export {
  Dialog,
  DialogTrigger,
  DialogPortal,
  DialogClose,
  DialogOverlay,
  DialogContent,
  DialogHeader,
  DialogFooter,
  DialogTitle,
  DialogDescription,
};
'''

    files["src/components/ui/dropdown-menu.tsx"] = '''\
import * as React from "react";
import * as DropdownMenuPrimitive from "@radix-ui/react-dropdown-menu";
import { cn } from "@/lib/utils";

const DropdownMenu = DropdownMenuPrimitive.Root;
const DropdownMenuTrigger = DropdownMenuPrimitive.Trigger;
const DropdownMenuGroup = DropdownMenuPrimitive.Group;
const DropdownMenuPortal = DropdownMenuPrimitive.Portal;
const DropdownMenuSub = DropdownMenuPrimitive.Sub;

const DropdownMenuContent = React.forwardRef<
  React.ElementRef<typeof DropdownMenuPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof DropdownMenuPrimitive.Content>
>(({ className, sideOffset = 4, ...props }, ref) => (
  <DropdownMenuPrimitive.Portal>
    <DropdownMenuPrimitive.Content
      ref={ref}
      sideOffset={sideOffset}
      className={cn("z-50 min-w-[8rem] overflow-hidden rounded-md border bg-popover p-1 text-popover-foreground shadow-md", className)}
      {...props}
    />
  </DropdownMenuPrimitive.Portal>
));
DropdownMenuContent.displayName = DropdownMenuPrimitive.Content.displayName;

const DropdownMenuItem = React.forwardRef<
  React.ElementRef<typeof DropdownMenuPrimitive.Item>,
  React.ComponentPropsWithoutRef<typeof DropdownMenuPrimitive.Item>
>(({ className, ...props }, ref) => (
  <DropdownMenuPrimitive.Item
    ref={ref}
    className={cn("relative flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none transition-colors focus:bg-accent focus:text-accent-foreground", className)}
    {...props}
  />
));
DropdownMenuItem.displayName = DropdownMenuPrimitive.Item.displayName;

const DropdownMenuLabel = React.forwardRef<
  React.ElementRef<typeof DropdownMenuPrimitive.Label>,
  React.ComponentPropsWithoutRef<typeof DropdownMenuPrimitive.Label>
>(({ className, ...props }, ref) => (
  <DropdownMenuPrimitive.Label ref={ref} className={cn("px-2 py-1.5 text-sm font-semibold", className)} {...props} />
));
DropdownMenuLabel.displayName = DropdownMenuPrimitive.Label.displayName;

const DropdownMenuSeparator = React.forwardRef<
  React.ElementRef<typeof DropdownMenuPrimitive.Separator>,
  React.ComponentPropsWithoutRef<typeof DropdownMenuPrimitive.Separator>
>(({ className, ...props }, ref) => (
  <DropdownMenuPrimitive.Separator ref={ref} className={cn("-mx-1 my-1 h-px bg-muted", className)} {...props} />
));
DropdownMenuSeparator.displayName = DropdownMenuPrimitive.Separator.displayName;

export {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuGroup,
  DropdownMenuPortal,
  DropdownMenuSub,
};
'''

    files["src/components/ui/toast.tsx"] = '''\
import * as React from "react";
import * as ToastPrimitives from "@radix-ui/react-toast";
import { cn } from "@/lib/utils";

const ToastProvider = ToastPrimitives.Provider;
const ToastViewport = React.forwardRef<
  React.ElementRef<typeof ToastPrimitives.Viewport>,
  React.ComponentPropsWithoutRef<typeof ToastPrimitives.Viewport>
>(({ className, ...props }, ref) => (
  <ToastPrimitives.Viewport
    ref={ref}
    className={cn("fixed top-0 z-[100] flex max-h-screen w-full flex-col-reverse p-4 sm:bottom-0 sm:right-0 sm:top-auto sm:flex-col md:max-w-[420px]", className)}
    {...props}
  />
));
ToastViewport.displayName = ToastPrimitives.Viewport.displayName;

const Toast = React.forwardRef<
  React.ElementRef<typeof ToastPrimitives.Root>,
  React.ComponentPropsWithoutRef<typeof ToastPrimitives.Root>
>(({ className, ...props }, ref) => (
  <ToastPrimitives.Root ref={ref} className={cn("group pointer-events-auto relative flex w-full items-center justify-between space-x-2 overflow-hidden rounded-md border p-4 pr-6 shadow-lg", className)} {...props} />
));
Toast.displayName = ToastPrimitives.Root.displayName;

const ToastTitle = React.forwardRef<
  React.ElementRef<typeof ToastPrimitives.Title>,
  React.ComponentPropsWithoutRef<typeof ToastPrimitives.Title>
>(({ className, ...props }, ref) => (
  <ToastPrimitives.Title ref={ref} className={cn("text-sm font-semibold", className)} {...props} />
));
ToastTitle.displayName = ToastPrimitives.Title.displayName;

const ToastDescription = React.forwardRef<
  React.ElementRef<typeof ToastPrimitives.Description>,
  React.ComponentPropsWithoutRef<typeof ToastPrimitives.Description>
>(({ className, ...props }, ref) => (
  <ToastPrimitives.Description ref={ref} className={cn("text-sm opacity-90", className)} {...props} />
));
ToastDescription.displayName = ToastPrimitives.Description.displayName;

const ToastClose = React.forwardRef<
  React.ElementRef<typeof ToastPrimitives.Close>,
  React.ComponentPropsWithoutRef<typeof ToastPrimitives.Close>
>(({ className, ...props }, ref) => (
  <ToastPrimitives.Close ref={ref} className={cn("absolute right-2 top-2 rounded-md p-1 opacity-0 transition-opacity hover:text-foreground focus:opacity-100 focus:outline-none group-hover:opacity-100", className)} {...props} />
));
ToastClose.displayName = ToastPrimitives.Close.displayName;

const ToastAction = React.forwardRef<
  React.ElementRef<typeof ToastPrimitives.Action>,
  React.ComponentPropsWithoutRef<typeof ToastPrimitives.Action>
>(({ className, ...props }, ref) => (
  <ToastPrimitives.Action ref={ref} className={cn("inline-flex h-8 shrink-0 items-center justify-center rounded-md border bg-transparent px-3 text-sm font-medium", className)} {...props} />
));
ToastAction.displayName = ToastPrimitives.Action.displayName;

type ToastProps = React.ComponentPropsWithoutRef<typeof Toast>;
type ToastActionElement = React.ReactElement<typeof ToastAction>;

export {
  type ToastProps,
  type ToastActionElement,
  ToastProvider,
  ToastViewport,
  Toast,
  ToastTitle,
  ToastDescription,
  ToastClose,
  ToastAction,
};
'''

    return files
