"""Convenience hooks generator — friendly façades over the per-operation hooks.

The plan (Phase F0.8) calls for ``useAuth``, ``useProfile`` (current user's
profile), ``useMarketplace`` and ``useWebSocket``. The per-operation hooks
emitted by :mod:`hooks_gen` already expose every endpoint, but pages should
not have to hand-wire login/logout/signup mutations every time. These
convenience hooks bundle the most common interactions so the agent fill
pass (and any hand-written page) can ``import { useAuth } from
"@/generated/hooks/use-current-user"`` and be done.
"""

from __future__ import annotations

from ..ir import FrontendIR

_HEADER = """\
// AUTO-GENERATED by Cosolvent Frontend Compiler v{version}
// spec_hash: {hash}
// DO NOT EDIT — changes will be overwritten on next compile
"""


def emit_convenience_hooks(ir: FrontendIR) -> dict[str, str]:
    """Emit ``useAuth`` / ``useCurrentProfile`` / ``useMarketplace`` modules."""

    files: dict[str, str] = {}
    files["src/generated/hooks/use-current-user.ts"] = _use_current_user(ir)
    files["src/generated/hooks/use-current-profile.ts"] = _use_current_profile(ir)
    files["src/generated/hooks/use-marketplace.ts"] = _use_marketplace(ir)
    return files


def _use_current_user(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

import {{ useCallback }} from "react";
import {{ useMutation, useQuery, useQueryClient }} from "@tanstack/react-query";
import * as auth from "../api/auth";
import {{ ApiError }} from "../api/client";
import type {{
  AuthResponse,
  BootstrapRequest,
  LoginRequest,
  SignupRequest,
  UserResponse,
}} from "../types";

export const currentUserKey = ["auth", "current-user"] as const;

export interface UseAuthResult {{
  user: UserResponse | null;
  isLoading: boolean;
  isAuthenticated: boolean;
  error: ApiError | null;
  refetch: () => Promise<unknown>;
  login: (input: LoginRequest) => Promise<AuthResponse>;
  signup: (input: SignupRequest) => Promise<AuthResponse>;
  logout: () => Promise<void>;
  bootstrap: (input: BootstrapRequest) => Promise<AuthResponse>;
  isLoggingIn: boolean;
  isLoggingOut: boolean;
  isSigningUp: boolean;
  isBootstrapping: boolean;
}}

/**
 * Top-level authentication hook.
 *
 * Wraps the generated ``/api/auth/*`` operations so pages can call a single
 * ``useAuth()`` and get the current user, login/signup/logout helpers, and
 * loading/error state. Mutations automatically invalidate the current-user
 * query so the UI re-renders without manual cache plumbing.
 */
export function useAuth(): UseAuthResult {{
  const qc = useQueryClient();

  const meQuery = useQuery<UserResponse, ApiError>({{
    queryKey: currentUserKey,
    queryFn: auth.getMe,
    retry: (failureCount, err) => {{
      if (err instanceof ApiError && (err.status === 401 || err.status === 403)) {{
        return false;
      }}
      return failureCount < 1;
    }},
    staleTime: 30 * 1000,
  }});

  const invalidate = () => qc.invalidateQueries({{ queryKey: ["auth"] }});

  const loginMutation = useMutation<AuthResponse, ApiError, LoginRequest>({{
    mutationFn: auth.login,
    onSuccess: invalidate,
  }});

  const signupMutation = useMutation<AuthResponse, ApiError, SignupRequest>({{
    mutationFn: auth.signup,
    onSuccess: invalidate,
  }});

  const logoutMutation = useMutation<unknown, ApiError, void>({{
    mutationFn: () => auth.logout(),
    onSuccess: () => {{
      qc.removeQueries({{ queryKey: currentUserKey }});
      invalidate();
    }},
  }});

  const bootstrapMutation = useMutation<AuthResponse, ApiError, BootstrapRequest>({{
    mutationFn: auth.bootstrap,
    onSuccess: invalidate,
  }});

  const login = useCallback(
    (input: LoginRequest) => loginMutation.mutateAsync(input),
    [loginMutation],
  );
  const signup = useCallback(
    (input: SignupRequest) => signupMutation.mutateAsync(input),
    [signupMutation],
  );
  const logout = useCallback(async () => {{
    await logoutMutation.mutateAsync();
  }}, [logoutMutation]);
  const bootstrap = useCallback(
    (input: BootstrapRequest) => bootstrapMutation.mutateAsync(input),
    [bootstrapMutation],
  );

  const apiError = (meQuery.error ?? null) as ApiError | null;
  const isAuthError =
    apiError instanceof ApiError && (apiError.status === 401 || apiError.status === 403);

  return {{
    user: meQuery.data ?? null,
    isLoading: meQuery.isLoading,
    isAuthenticated: !!meQuery.data,
    error: isAuthError ? null : apiError,
    refetch: meQuery.refetch,
    login,
    signup,
    logout,
    bootstrap,
    isLoggingIn: loginMutation.isPending,
    isLoggingOut: logoutMutation.isPending,
    isSigningUp: signupMutation.isPending,
    isBootstrapping: bootstrapMutation.isPending,
  }};
}}
"""


def _use_current_profile(ir: FrontendIR) -> str:
    """Emit ``useCurrentProfile`` — resolves the user's role and fetches /me."""

    role_to_path: dict[str, str] = {
        entity.slug: f"/api/roles/{entity.slug}/me" for entity in ir.entities
    }
    role_lookup = ",\n  ".join(
        f'"{slug}": "{path}"' for slug, path in sorted(role_to_path.items())
    )

    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

import {{ useQuery }} from "@tanstack/react-query";
import {{ ApiError, apiFetch }} from "../api/client";
import {{ useAuth }} from "./use-current-user";

const ROLE_TO_ME_PATH: Record<string, string> = {{
  {role_lookup}
}};

export interface UseCurrentProfileResult<T = unknown> {{
  profile: T | null;
  isLoading: boolean;
  error: ApiError | null;
  participantType: string | null;
  refetch: () => Promise<unknown>;
}}

/**
 * Fetch the current user's profile via their role-aliased ``/me`` endpoint.
 *
 * Returns ``{{ profile: null }}`` while the user is unauthenticated or before
 * onboarding has produced a profile. The ``participantType`` field reflects
 * the active marketplace role (``producer``, ``buyer``, …).
 */
export function useCurrentProfile<T = unknown>(): UseCurrentProfileResult<T> {{
  const {{ user, isLoading: authLoading }} = useAuth();
  const participantType = user?.participant_type ?? null;
  const path = participantType ? ROLE_TO_ME_PATH[participantType] : undefined;

  const query = useQuery<T, ApiError>({{
    queryKey: ["profiles", "current", participantType ?? "anon"],
    queryFn: () => apiFetch<T>(path as string),
    enabled: !!path,
    retry: (failureCount, err) => {{
      if (err instanceof ApiError && (err.status === 401 || err.status === 403 || err.status === 404)) {{
        return false;
      }}
      return failureCount < 1;
    }},
  }});

  return {{
    profile: query.data ?? null,
    isLoading: authLoading || query.isLoading,
    error: (query.error ?? null) as ApiError | null,
    participantType,
    refetch: query.refetch,
  }};
}}

/** Alias so consumers can write ``useProfile()`` per the F0 plan vocabulary. */
export const useProfile = useCurrentProfile;
"""


def _use_marketplace(ir: FrontendIR) -> str:
    """Emit ``useMarketplace`` — exposes the generated marketplace constants."""

    participant_lines: list[str] = []
    for entity in ir.entities:
        participant_lines.append(
            f'    {{ slug: "{entity.slug}", name: "{entity.name}", '
            f'role: "{entity.role}", visibleInSearch: '
            f'{ "true" if entity.permissions.visible_in_search else "false" } }}'
        )
    participants = ",\n".join(participant_lines)

    industry = ir.marketplace.industry or ""

    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

import {{ useMemo }} from "react";
import {{
  marketplaceDescription,
  marketplaceName,
  navigationItems,
  participantTypes,
}} from "../navigation";
import type {{ NavItem }} from "../navigation";

export interface MarketplaceParticipant {{
  slug: string;
  name: string;
  role: string;
  visibleInSearch: boolean;
}}

export interface MarketplaceContext {{
  name: string;
  description: string;
  industry: string;
  participants: MarketplaceParticipant[];
  participantTypes: typeof participantTypes;
  navigation: NavItem[];
  navigationFor: (role: string | null | undefined) => NavItem[];
  participantBySlug: (slug: string | null | undefined) => MarketplaceParticipant | null;
}}

const PARTICIPANTS: MarketplaceParticipant[] = [
{participants},
];

/**
 * Returns marketplace metadata and helpers derived from ``marketplace.yaml``.
 *
 * Centralises access to the generated constants so layouts and pages can
 * render dynamic copy without importing from multiple modules.
 */
export function useMarketplace(): MarketplaceContext {{
  return useMemo(() => {{
    const navigationFor = (role: string | null | undefined): NavItem[] => {{
      if (!role) return navigationItems.filter((n) => n.roles.includes("anon"));
      return navigationItems.filter(
        (n) => n.roles.includes(role) || n.roles.includes("*"),
      );
    }};

    const participantBySlug = (
      slug: string | null | undefined,
    ): MarketplaceParticipant | null =>
      slug ? PARTICIPANTS.find((p) => p.slug === slug) ?? null : null;

    return {{
      name: marketplaceName,
      description: marketplaceDescription,
      industry: "{industry}",
      participants: PARTICIPANTS,
      participantTypes,
      navigation: navigationItems,
      navigationFor,
      participantBySlug,
    }};
  }}, []);
}}
"""
