"""Generate React Query hooks from the FrontendIR.

Emits ``src/generated/hooks/use-{module}.ts`` files with:
- Query key factories for deterministic cache management
- useQuery hooks for GET operations
- useMutation hooks for POST/PUT/DELETE operations
- Automatic cache invalidation on mutation success
"""

from __future__ import annotations

from collections import defaultdict

from ..ir import FrontendIR, OperationIR
from ..naming import api_client_filename, hook_filename, slug_to_camel, slug_to_pascal

_HEADER = """\
// AUTO-GENERATED by Cosolvent Frontend Compiler v{version}
// spec_hash: {hash}
// DO NOT EDIT — changes will be overwritten on next compile
"""


def emit_hooks(ir: FrontendIR) -> dict[str, str]:
    files: dict[str, str] = {}

    ops_by_module: dict[str, list[OperationIR]] = defaultdict(list)
    for op in ir.operations:
        ops_by_module[op.module].append(op)

    for module, ops in sorted(ops_by_module.items()):
        filename = hook_filename(module)
        files[f"src/generated/hooks/{filename}"] = _module_hooks(ir, module, ops)

    if "communication" in ops_by_module:
        files["src/generated/hooks/use-websocket.ts"] = _websocket_hooks(ir)

    return files


def _module_hooks(ir: FrontendIR, module: str, ops: list[OperationIR]) -> str:
    lines: list[str] = [_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)]

    lines.append(
        'import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";'
    )
    api_module = api_client_filename(module).replace(".ts", "")
    lines.append(f'import * as api from "../api/{api_module}";')
    lines.append("")

    lines.append(_key_factory(module, ops))

    get_ops = [o for o in ops if o.method == "GET"]
    mut_ops = [o for o in ops if o.method != "GET"]

    for op in sorted(get_ops, key=lambda o: o.id):
        lines.append(_query_hook(module, op))

    for op in sorted(mut_ops, key=lambda o: o.id):
        lines.append(_mutation_hook(module, op, get_ops))

    return "\n".join(lines) + "\n"


def _key_factory(module: str, ops: list[OperationIR]) -> str:
    """Emit a typed query-key factory for one module.

    EVERY entry includes the operation id as a discriminator so two queries
    in the same module never collide on the same cache slot. Without this,
    React Query overwrites one query's data with another's last response —
    e.g. ``useDashboard()`` and ``useListApplications()`` would both store
    under ``["admin"]`` and the late-arriving response wins.
    """
    camel = slug_to_camel(module)
    lines: list[str] = []
    lines.append(f"export const {camel}Keys = {{")
    lines.append(f'  all: ["{module}"] as const,')

    seen: set[str] = set()
    for op in sorted(ops, key=lambda o: o.id):
        if op.method != "GET":
            continue

        key_name = slug_to_camel(op.id)
        if key_name in seen:
            continue
        seen.add(key_name)

        prefix_parts = [f"...{camel}Keys.all"]
        if op.entity_slug:
            prefix_parts.append(f'"{op.entity_slug}"')
        # Always include the operation id — this is what makes the cache slot
        # unique and prevents the all-admin-queries-collide bug.
        prefix_parts.append(f'"{op.id}"')

        if op.path_params:
            param_list = ", ".join(f"{p}: string" for p in op.path_params)
            extra_parts = ", ".join(op.path_params)
            lines.append(
                f"  {key_name}: ({param_list}) => "
                f"[{', '.join(prefix_parts)}, {extra_parts}] as const,"
            )
        else:
            lines.append(
                f"  {key_name}: () => "
                f"[{', '.join(prefix_parts)}] as const,"
            )

    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def _query_hook(module: str, op: OperationIR) -> str:
    hook_name = _derive_hook_name(op)
    camel_keys = slug_to_camel(module) + "Keys"
    key_fn = slug_to_camel(op.id)

    path_params = list(op.path_params)
    query_params = [qp for qp in op.query_params]

    sig_parts: list[str] = []
    call_parts: list[str] = []
    key_parts: list[str] = []

    for p in path_params:
        sig_parts.append(f"{p}: string")
        call_parts.append(p)
        key_parts.append(p)
    for qp in query_params:
        marker = "" if qp.required else "?"
        sig_parts.append(f"{qp.name}{marker}: {qp.ts_type}")
        call_parts.append(qp.name)

    sig = ", ".join(sig_parts)
    call_args = ", ".join(call_parts)
    key_args = ", ".join(key_parts)

    lines: list[str] = []
    lines.append(f"export function {hook_name}({sig}) {{")
    lines.append("  return useQuery({")
    lines.append(f"    queryKey: {camel_keys}.{key_fn}({key_args}),")
    # Always wrap in an arrow function so the queryFn signature stays
    # compatible with React Query's ``QueryFunctionContext`` requirement,
    # regardless of whether the API client takes path or query params.
    lines.append(f"    queryFn: () => api.{op.id}({call_args}),")
    # Always refetch on remount and treat data as immediately stale. Without
    # this, navigating away and back can keep showing an outdated snapshot,
    # which is especially confusing for admin lists where the underlying
    # rows mutate frequently.
    lines.append('    staleTime: 0,')
    lines.append('    refetchOnMount: "always",')
    if path_params:
        # Avoid calling ``/api/...//...`` when a path segment is still empty
        # (e.g. ``useDraft("")`` before the UI knows the participant type).
        enabled_expr = " && ".join(f"Boolean({p})" for p in path_params)
        lines.append(f"    enabled: {enabled_expr},")
    lines.append("  });")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _mutation_hook(
    module: str,
    op: OperationIR,
    get_ops: list[OperationIR],
) -> str:
    hook_name = _derive_hook_name(op)
    camel_keys = slug_to_camel(module) + "Keys"

    arg_names: list[str] = []
    for p in op.path_params:
        arg_names.append(p)
    for qp in op.query_params:
        arg_names.append(qp.name)
    if op.request_schema:
        arg_names.append("body")

    lines: list[str] = []
    lines.append(f"export function {hook_name}() {{")
    lines.append("  const qc = useQueryClient();")
    lines.append("  return useMutation({")

    if not arg_names:
        lines.append(f"    mutationFn: () => api.{op.id}(),")
    elif len(arg_names) == 1:
        lines.append(
            f"    mutationFn: (input: Parameters<typeof api.{op.id}>[0]) => "
            f"api.{op.id}(input),"
        )
    else:
        # Bundle multiple positional args into a single object so React Query's
        # ``MutationFunction`` (which only accepts a single variable) is happy.
        # Use ``Parameters<typeof api.fn>[N]`` so we never need to import the
        # underlying request schema types into the hook module.
        field_lines = ", ".join(
            f"{n}: Parameters<typeof api.{op.id}>[{i}]"
            for i, n in enumerate(arg_names)
        )
        call_args = ", ".join(f"input.{n}" for n in arg_names)
        lines.append(
            f"    mutationFn: (input: {{ {field_lines} }}) => "
            f"api.{op.id}({call_args}),"
        )

    invalidation_keys = _find_invalidation_targets(op, get_ops, camel_keys)
    if invalidation_keys:
        lines.append("    onSuccess: () => {")
        for key_expr in invalidation_keys:
            lines.append(f"      qc.invalidateQueries({{ queryKey: {key_expr} }});")
        lines.append("    },")

    lines.append("  });")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _find_invalidation_targets(
    mut_op: OperationIR,
    get_ops: list[OperationIR],
    camel_keys: str,
) -> list[str]:
    """Determine which query keys to invalidate when a mutation succeeds."""
    targets: list[str] = []

    if mut_op.entity_slug:
        for get_op in get_ops:
            if get_op.entity_slug == mut_op.entity_slug and not get_op.path_params:
                key_fn = slug_to_camel(get_op.id)
                targets.append(f"{camel_keys}.{key_fn}()")

    if not targets:
        targets.append(f"{camel_keys}.all")

    return targets


_REACT_QUERY_RESERVED = {
    "useQuery",
    "useMutation",
    "useQueryClient",
    "useInfiniteQuery",
    "useQueries",
    "useSuspenseQuery",
}


def _derive_hook_name(op: OperationIR) -> str:
    base = op.id
    if base.startswith("get"):
        body = base[3:]
        candidate = f"use{body}"
    else:
        candidate = f"use{base[0].upper()}{base[1:]}"

    # Avoid colliding with React Query's own hooks (e.g. ``query`` →
    # ``useQuery``). Prefix with the module's PascalCase name to stay
    # deterministic while remaining readable.
    if candidate in _REACT_QUERY_RESERVED:
        suffix = base[0].upper() + base[1:]
        candidate = f"use{slug_to_pascal(op.module)}{suffix}"

    return candidate


def _websocket_hooks(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

import {{ useCallback, useEffect, useMemo, useRef, useState }} from "react";

export type SocketConnectionState = "idle" | "connecting" | "connected" | "closed" | "error";

export type ConversationSocketEvent = {{
  type: string;
  [key: string]: unknown;
}};

export interface ConversationWebSocketOptions {{
  enabled?: boolean;
  reconnect?: boolean;
  reconnectDelayMs?: number;
  onEvent?: (event: ConversationSocketEvent) => void;
}}

const API_BASE = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:18000";

function toWebSocketBase(apiBase: string): string {{
  if (apiBase.startsWith("https://")) return apiBase.replace("https://", "wss://");
  if (apiBase.startsWith("http://")) return apiBase.replace("http://", "ws://");
  return apiBase;
}}

export function useConversationWebSocket(
  conversationId: string | null | undefined,
  options: ConversationWebSocketOptions = {{}},
) {{
  const {{
    enabled = true,
    reconnect = true,
    reconnectDelayMs = 1500,
    onEvent,
  }} = options;

  const socketRef = useRef<WebSocket | null>(null);
  const reconnectTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  // Hold the *latest* onEvent in a ref so callers can pass an inline closure
  // without re-running the connection effect on every render — that loop
  // (effect re-runs → close/open socket → setState → re-render → effect
  // re-runs) was hitting React's "Maximum update depth exceeded" guard.
  const onEventRef = useRef<ConversationWebSocketOptions["onEvent"]>(onEvent);
  const shouldReconnectRef = useRef(reconnect);
  const reconnectDelayRef = useRef(reconnectDelayMs);

  const [state, setState] = useState<SocketConnectionState>("idle");
  const [lastEvent, setLastEvent] = useState<ConversationSocketEvent | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {{
    onEventRef.current = onEvent;
  }}, [onEvent]);

  useEffect(() => {{
    shouldReconnectRef.current = reconnect;
  }}, [reconnect]);

  useEffect(() => {{
    reconnectDelayRef.current = reconnectDelayMs;
  }}, [reconnectDelayMs]);

  const wsUrl = useMemo(() => {{
    if (!conversationId) return null;
    const base = toWebSocketBase(API_BASE);
    // Backend mounts the communication router at ``/api`` and exposes the
    // WS route as ``/ws/{{conversation_id}}`` — full path is /api/ws/...
    // (no /communication segment).
    return `${{base}}/api/ws/${{encodeURIComponent(conversationId)}}`;
  }}, [conversationId]);

  // Single connection lifecycle. Depends only on enabled + wsUrl so React
  // state changes don't tear down/rebuild the socket.
  useEffect(() => {{
    if (!enabled || !wsUrl) {{
      setState("idle");
      return;
    }}

    let cancelled = false;

    const fetchTicket = async (): Promise<string | null> => {{
      try {{
        const res = await fetch(`${{API_BASE}}/api/auth/ws-ticket`, {{
          credentials: "include",
        }});
        if (!res.ok) return null;
        const body = (await res.json()) as {{ ticket?: string }};
        return body?.ticket ?? null;
      }} catch {{
        return null;
      }}
    }};

    const open = async () => {{
      if (cancelled) return;
      setState("connecting");
      setError(null);

      // HttpOnly session cookies aren't reliably attached to cross-port WS
      // upgrades, so the JS client exchanges the cookie for a one-shot
      // ticket and passes it in the auth message.
      const ticket = await fetchTicket();
      if (cancelled) return;
      if (!ticket) {{
        setState("error");
        setError("Could not obtain WebSocket auth ticket. Are you signed in?");
        if (shouldReconnectRef.current) {{
          if (reconnectTimerRef.current) clearTimeout(reconnectTimerRef.current);
          reconnectTimerRef.current = setTimeout(() => {{
            reconnectTimerRef.current = null;
            void open();
          }}, reconnectDelayRef.current);
        }}
        return;
      }}

      const ws = new WebSocket(wsUrl);
      socketRef.current = ws;

      ws.onopen = () => {{
        if (cancelled) return;
        setState("connected");
        try {{
          ws.send(JSON.stringify({{ type: "auth", ticket }}));
        }} catch {{
          /* swallow — onerror/onclose will drive recovery */
        }}
      }};

      ws.onmessage = (evt: MessageEvent) => {{
        try {{
          const parsed = JSON.parse(evt.data) as ConversationSocketEvent;
          setLastEvent(parsed);
          onEventRef.current?.(parsed);
        }} catch {{
          // Ignore non-JSON frames.
        }}
      }};

      ws.onerror = () => {{
        if (cancelled) return;
        setState("error");
        setError("WebSocket connection error");
      }};

      ws.onclose = () => {{
        if (cancelled) return;
        setState("closed");
        socketRef.current = null;
        if (shouldReconnectRef.current) {{
          if (reconnectTimerRef.current) clearTimeout(reconnectTimerRef.current);
          reconnectTimerRef.current = setTimeout(() => {{
            reconnectTimerRef.current = null;
            void open();
          }}, reconnectDelayRef.current);
        }}
      }};
    }};

    void open();

    return () => {{
      cancelled = true;
      if (reconnectTimerRef.current) {{
        clearTimeout(reconnectTimerRef.current);
        reconnectTimerRef.current = null;
      }}
      const sock = socketRef.current;
      socketRef.current = null;
      if (sock) {{
        // Detach handlers before close() so a queued onclose from a
        // half-open socket can't schedule a stale reconnect.
        sock.onopen = null;
        sock.onmessage = null;
        sock.onerror = null;
        sock.onclose = null;
        try {{ sock.close(); }} catch {{ /* noop */ }}
      }}
    }};
  }}, [enabled, wsUrl]);

  const sendEvent = useCallback((event: ConversationSocketEvent) => {{
    if (!socketRef.current || socketRef.current.readyState !== WebSocket.OPEN) return false;
    socketRef.current.send(JSON.stringify(event));
    return true;
  }}, []);

  const sendMessage = useCallback(
    (content: string, contentType = "text") => sendEvent({{ type: "message", content, content_type: contentType }}),
    [sendEvent],
  );

  const ping = useCallback(() => sendEvent({{ type: "ping" }}), [sendEvent]);

  // Manual retry: bounce the socket and let the existing onclose handler
  // schedule the reconnect. No effect dep churn — the connection effect
  // is unaware of this path.
  const reconnectNow = useCallback(() => {{
    shouldReconnectRef.current = true;
    if (reconnectTimerRef.current) {{
      clearTimeout(reconnectTimerRef.current);
      reconnectTimerRef.current = null;
    }}
    const sock = socketRef.current;
    if (sock) {{
      try {{ sock.close(); }} catch {{ /* noop */ }}
    }}
  }}, []);

  return {{
    state,
    lastEvent,
    error,
    sendEvent,
    sendMessage,
    ping,
    reconnect: reconnectNow,
  }};
}}
"""
