"""Generate React Query hooks from the FrontendIR.

Emits ``src/generated/hooks/use-{module}.ts`` files with:
- Query key factories for deterministic cache management
- useQuery hooks for GET operations
- useMutation hooks for POST/PUT/DELETE operations
- Automatic cache invalidation on mutation success
"""

from __future__ import annotations

from collections import defaultdict

from ..ir import FrontendIR, OperationIR
from ..naming import api_client_filename, hook_filename, slug_to_camel

_HEADER = """\
// AUTO-GENERATED by Cosolvent Frontend Compiler v{version}
// spec_hash: {hash}
// DO NOT EDIT — changes will be overwritten on next compile
"""


def emit_hooks(ir: FrontendIR) -> dict[str, str]:
    files: dict[str, str] = {}

    ops_by_module: dict[str, list[OperationIR]] = defaultdict(list)
    for op in ir.operations:
        ops_by_module[op.module].append(op)

    for module, ops in sorted(ops_by_module.items()):
        filename = hook_filename(module)
        files[f"src/generated/hooks/{filename}"] = _module_hooks(ir, module, ops)

    if "communication" in ops_by_module:
        files["src/generated/hooks/use-websocket.ts"] = _websocket_hooks(ir)

    return files


def _module_hooks(ir: FrontendIR, module: str, ops: list[OperationIR]) -> str:
    lines: list[str] = [_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)]

    lines.append(
        'import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";'
    )
    api_module = api_client_filename(module).replace(".ts", "")
    lines.append(f'import * as api from "../api/{api_module}";')
    lines.append("")

    lines.append(_key_factory(module, ops))

    get_ops = [o for o in ops if o.method == "GET"]
    mut_ops = [o for o in ops if o.method != "GET"]

    for op in sorted(get_ops, key=lambda o: o.id):
        lines.append(_query_hook(module, op))

    for op in sorted(mut_ops, key=lambda o: o.id):
        lines.append(_mutation_hook(module, op, get_ops))

    return "\n".join(lines) + "\n"


def _key_factory(module: str, ops: list[OperationIR]) -> str:
    camel = slug_to_camel(module)
    lines: list[str] = []
    lines.append(f"export const {camel}Keys = {{")
    lines.append(f'  all: ["{module}"] as const,')

    seen: set[str] = set()
    for op in sorted(ops, key=lambda o: o.id):
        if op.method != "GET":
            continue

        key_name = slug_to_camel(op.id)
        if key_name in seen:
            continue
        seen.add(key_name)

        if op.path_params:
            param_list = ", ".join(f"{p}: string" for p in op.path_params)
            entity_part = f', "{op.entity_slug}"' if op.entity_slug else ""
            extra_parts = ", ".join(p for p in op.path_params)
            lines.append(
                f"  {key_name}: ({param_list}) => "
                f'[...{camel}Keys.all{entity_part}, {extra_parts}] as const,'
            )
        else:
            entity_part = f', "{op.entity_slug}"' if op.entity_slug else ""
            kind_part = f', "{op.kind}"' if op.kind != op.id else ""
            lines.append(
                f"  {key_name}: () => "
                f"[...{camel}Keys.all{entity_part}{kind_part}] as const,"
            )

    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def _query_hook(module: str, op: OperationIR) -> str:
    hook_name = _derive_hook_name(op)
    camel_keys = slug_to_camel(module) + "Keys"
    key_fn = slug_to_camel(op.id)

    lines: list[str] = []

    if op.path_params:
        param_list = ", ".join(f"{p}: string" for p in op.path_params)
        call_args = ", ".join(op.path_params)
        lines.append(f"export function {hook_name}({param_list}) {{")
        lines.append("  return useQuery({")
        lines.append(f"    queryKey: {camel_keys}.{key_fn}({call_args}),")
        lines.append(f"    queryFn: () => api.{op.id}({call_args}),")
    else:
        lines.append(f"export function {hook_name}() {{")
        lines.append("  return useQuery({")
        lines.append(f"    queryKey: {camel_keys}.{key_fn}(),")
        lines.append(f"    queryFn: api.{op.id},")

    lines.append("  });")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _mutation_hook(
    module: str,
    op: OperationIR,
    get_ops: list[OperationIR],
) -> str:
    hook_name = _derive_hook_name(op)
    camel_keys = slug_to_camel(module) + "Keys"

    lines: list[str] = []
    lines.append(f"export function {hook_name}() {{")
    lines.append("  const qc = useQueryClient();")
    lines.append("  return useMutation({")
    lines.append(f"    mutationFn: api.{op.id},")

    invalidation_keys = _find_invalidation_targets(op, get_ops, camel_keys)
    if invalidation_keys:
        lines.append("    onSuccess: () => {")
        for key_expr in invalidation_keys:
            lines.append(f"      qc.invalidateQueries({{ queryKey: {key_expr} }});")
        lines.append("    },")

    lines.append("  });")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _find_invalidation_targets(
    mut_op: OperationIR,
    get_ops: list[OperationIR],
    camel_keys: str,
) -> list[str]:
    """Determine which query keys to invalidate when a mutation succeeds."""
    targets: list[str] = []

    if mut_op.entity_slug:
        for get_op in get_ops:
            if get_op.entity_slug == mut_op.entity_slug and not get_op.path_params:
                key_fn = slug_to_camel(get_op.id)
                targets.append(f"{camel_keys}.{key_fn}()")

    if not targets:
        targets.append(f"{camel_keys}.all")

    return targets


def _derive_hook_name(op: OperationIR) -> str:
    base = op.id
    if base.startswith("get"):
        body = base[3:]
        return f"use{body}"
    return f"use{base[0].upper()}{base[1:]}"


def _websocket_hooks(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

import {{ useCallback, useEffect, useMemo, useRef, useState }} from "react";

export type SocketConnectionState = "idle" | "connecting" | "connected" | "closed" | "error";

export type ConversationSocketEvent = {{
  type: string;
  [key: string]: unknown;
}};

export interface ConversationWebSocketOptions {{
  enabled?: boolean;
  reconnect?: boolean;
  reconnectDelayMs?: number;
  onEvent?: (event: ConversationSocketEvent) => void;
}}

const API_BASE = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:18000";

function toWebSocketBase(apiBase: string): string {{
  if (apiBase.startsWith("https://")) return apiBase.replace("https://", "wss://");
  if (apiBase.startsWith("http://")) return apiBase.replace("http://", "ws://");
  return apiBase;
}}

export function useConversationWebSocket(
  conversationId: string | null | undefined,
  options: ConversationWebSocketOptions = {{}},
) {{
  const {{
    enabled = true,
    reconnect = true,
    reconnectDelayMs = 1500,
    onEvent,
  }} = options;

  const socketRef = useRef<WebSocket | null>(null);
  const reconnectTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const shouldReconnectRef = useRef(reconnect);

  const [state, setState] = useState<SocketConnectionState>("idle");
  const [lastEvent, setLastEvent] = useState<ConversationSocketEvent | null>(null);
  const [error, setError] = useState<string | null>(null);

  const wsUrl = useMemo(() => {{
    if (!conversationId) return null;
    const base = toWebSocketBase(API_BASE);
    return `${{base}}/api/communication/ws/${{encodeURIComponent(conversationId)}}`;
  }}, [conversationId]);

  const clearReconnectTimer = useCallback(() => {{
    if (reconnectTimerRef.current) {{
      clearTimeout(reconnectTimerRef.current);
      reconnectTimerRef.current = null;
    }}
  }}, []);

  const closeSocket = useCallback(() => {{
    if (socketRef.current) {{
      socketRef.current.close();
      socketRef.current = null;
    }}
  }}, []);

  const connect = useCallback(() => {{
    if (!enabled || !wsUrl) return;
    setState("connecting");
    setError(null);

    const ws = new WebSocket(wsUrl);
    socketRef.current = ws;

    ws.onopen = () => {{
      setState("connected");
      ws.send(JSON.stringify({{ type: "auth" }}));
    }};

    ws.onmessage = (evt: MessageEvent) => {{
      try {{
        const parsed = JSON.parse(evt.data) as ConversationSocketEvent;
        setLastEvent(parsed);
        onEvent?.(parsed);
      }} catch {{
        // Ignore non-JSON frames.
      }}
    }};

    ws.onerror = () => {{
      setState("error");
      setError("WebSocket connection error");
    }};

    ws.onclose = () => {{
      setState("closed");
      socketRef.current = null;
      if (shouldReconnectRef.current && reconnect) {{
        clearReconnectTimer();
        reconnectTimerRef.current = setTimeout(() => {{
          connect();
        }}, reconnectDelayMs);
      }}
    }};
  }}, [enabled, wsUrl, onEvent, reconnect, reconnectDelayMs, clearReconnectTimer]);

  useEffect(() => {{
    shouldReconnectRef.current = reconnect;
  }}, [reconnect]);

  useEffect(() => {{
    if (!enabled || !wsUrl) {{
      clearReconnectTimer();
      closeSocket();
      setState("idle");
      return;
    }}

    connect();
    return () => {{
      shouldReconnectRef.current = false;
      clearReconnectTimer();
      closeSocket();
    }};
  }}, [enabled, wsUrl, connect, clearReconnectTimer, closeSocket]);

  const sendEvent = useCallback((event: ConversationSocketEvent) => {{
    if (!socketRef.current || socketRef.current.readyState !== WebSocket.OPEN) return false;
    socketRef.current.send(JSON.stringify(event));
    return true;
  }}, []);

  const sendMessage = useCallback(
    (content: string, contentType = "text") => sendEvent({{ type: "message", content, content_type: contentType }}),
    [sendEvent],
  );

  const ping = useCallback(() => sendEvent({{ type: "ping" }}), [sendEvent]);

  const reconnectNow = useCallback(() => {{
    shouldReconnectRef.current = reconnect;
    clearReconnectTimer();
    closeSocket();
    connect();
  }}, [reconnect, clearReconnectTimer, closeSocket, connect]);

  return {{
    state,
    lastEvent,
    error,
    sendEvent,
    sendMessage,
    ping,
    reconnect: reconnectNow,
  }};
}}
"""
