"""Generate the navigation configuration from the FrontendIR.

Emits ``src/generated/navigation.ts`` — a typed array of sidebar items
consumed by the layout sidebar component.
"""

from __future__ import annotations

from ..ir import FrontendIR

_HEADER = """\
// AUTO-GENERATED by Cosolvent Frontend Compiler v{version}
// spec_hash: {hash}
// DO NOT EDIT — changes will be overwritten on next compile
"""


def emit_navigation(ir: FrontendIR) -> dict[str, str]:
    lines: list[str] = [_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)]

    icon_names = sorted({item.icon for item in ir.navigation.items})
    icons_import = ", ".join(icon_names)
    lines.append(f'import {{ {icons_import} }} from "lucide-react";')
    lines.append('import type { LucideIcon } from "lucide-react";')
    lines.append("")

    lines.append("export interface NavItem {")
    lines.append("  label: string;")
    lines.append("  route: string;")
    lines.append("  icon: LucideIcon;")
    lines.append("  roles: string[];")
    lines.append("}")
    lines.append("")

    lines.append("export const navigationItems: NavItem[] = [")
    for item in ir.navigation.items:
        roles = ", ".join(f'"{r}"' for r in item.roles)
        lines.append(
            f'  {{ label: "{item.label}", route: "{item.route}", '
            f"icon: {item.icon}, roles: [{roles}] }},"
        )
    lines.append("];")
    lines.append("")

    # Escape any double-quotes / backslashes in user-supplied strings so they
    # paste safely into a TS string literal.
    name = ir.marketplace.name.replace("\\", "\\\\").replace('"', '\\"')
    desc = ir.marketplace.description.replace("\\", "\\\\").replace('"', '\\"')
    logo = ir.theme.logo_emoji.replace("\\", "\\\\").replace('"', '\\"')
    lines.append(f'export const marketplaceName = "{name}";')
    lines.append(f'export const marketplaceDescription = "{desc}";')
    lines.append(f'export const marketplaceLogo = "{logo}";')
    lines.append("")

    lines.append("export const participantTypes = [")
    for entity in ir.entities:
        lines.append(
            f'  {{ slug: "{entity.slug}", name: "{entity.name}", role: "{entity.role}" }},'
        )
    lines.append("] as const;")
    lines.append("")

    return {"src/generated/navigation.ts": "\n".join(lines) + "\n"}
