"""Emit a typed manifest of all OpenAPI operations for the API explorer UI."""

from __future__ import annotations

import json

from ..ir import FrontendIR, OperationIR

_HEADER = """\
// AUTO-GENERATED by Cosolvent Frontend Compiler v{version}
// spec_hash: {hash}
// DO NOT EDIT — changes will be overwritten on next compile

"""


def _body_kind(op: OperationIR) -> str:
    if op.method in ("GET", "DELETE"):
        return "none"
    if op.method == "POST" and op.path == "/api/files/upload":
        return "multipart"
    return "json"


def emit_operations_manifest(ir: FrontendIR) -> dict[str, str]:
    rows: list[dict] = []
    for op in sorted(ir.operations, key=lambda o: (o.module, o.path, o.method)):
        rows.append(
            {
                "id": op.id,
                "method": op.method,
                "path": op.path,
                "module": op.module,
                "pathParams": list(op.path_params),
                "queryParams": [
                    {"name": qp.name, "required": qp.required, "tsType": qp.ts_type}
                    for qp in op.query_params
                ],
                "bodyKind": _body_kind(op),
                "authRequired": op.auth_required,
            }
        )

    header = _HEADER.format(version=ir.generator_version, hash=ir.spec_hash)
    body = (
        "export type OperationManifestEntry = {\n"
        '  id: string;\n'
        '  method: string;\n'
        '  path: string;\n'
        '  module: string;\n'
        '  pathParams: string[];\n'
        '  queryParams: { name: string; required: boolean; tsType: string }[];\n'
        '  bodyKind: "none" | "json" | "multipart";\n'
        "  authRequired: boolean;\n"
        "};\n\n"
        "export const operationsManifest: OperationManifestEntry[] = "
        + json.dumps(rows, indent=2)
        + ";\n"
    )
    return {"src/generated/operations-manifest.ts": header + body}
