"""Generate Next.js App Router pages and layouts from the FrontendIR.

Emits:
- Root layout with providers
- Auth layout (centered card)
- Dashboard layout (sidebar shell)
- Landing page (redirect)
- Login / Signup pages
- Dashboard page
- Profile view / edit pages
- Search page
- Profile detail page
- Conversation list / detail pages
- Notification page
- Public registration page
"""

from __future__ import annotations

from ..ir import FrontendIR
from ..naming import slug_to_pascal

_HEADER = """\
// AUTO-GENERATED by Cosolvent Frontend Compiler v{version}
// spec_hash: {hash}
// DO NOT EDIT — changes will be overwritten on next compile
"""


def emit_routes(ir: FrontendIR) -> dict[str, str]:
    files: dict[str, str] = {}

    files["src/app/layout.tsx"] = _root_layout(ir)
    files["src/app/page.tsx"] = _landing_page(ir)

    files["src/app/(auth)/layout.tsx"] = _auth_layout(ir)
    files["src/app/(auth)/login/page.tsx"] = _login_page(ir)

    page_ids = {p.id for p in ir.pages}

    if "signup" in page_ids:
        files["src/app/(auth)/signup/page.tsx"] = _signup_page(ir)

    files["src/app/(dashboard)/layout.tsx"] = _dashboard_layout(ir)
    files["src/app/(dashboard)/page.tsx"] = _dashboard_page(ir)

    files["src/app/(dashboard)/profile/page.tsx"] = _profile_view_page(ir)
    files["src/app/(dashboard)/profile/edit/page.tsx"] = _profile_edit_page(ir)

    if "search" in page_ids:
        files["src/app/(dashboard)/search/page.tsx"] = _search_page(ir)

    files["src/app/(dashboard)/profiles/[id]/page.tsx"] = _profile_detail_page(ir)

    if "conversations" in page_ids:
        files["src/app/(dashboard)/conversations/page.tsx"] = _conversations_page(ir)
        files["src/app/(dashboard)/conversations/[id]/page.tsx"] = (
            _conversation_detail_page(ir)
        )

    if "notifications" in page_ids:
        files["src/app/(dashboard)/notifications/page.tsx"] = _notifications_page(ir)

    if "register" in page_ids:
        files["src/app/register/[type]/page.tsx"] = _register_page(ir)

    files["src/lib/providers.tsx"] = _providers(ir)

    return files


# ── Root layout ───────────────────────────────────────────────────────


def _root_layout(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
import type {{ Metadata }} from "next";
import {{ Inter }} from "next/font/google";
import "@/styles/globals.css";
import {{ Providers }} from "@/lib/providers";

const inter = Inter({{ subsets: ["latin"] }});

export const metadata: Metadata = {{
  title: "{ir.marketplace.name}",
  description: "{ir.marketplace.description}",
}};

export default function RootLayout({{
  children,
}}: {{
  children: React.ReactNode;
}}) {{
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={{inter.className}}>
        <Providers>{{children}}</Providers>
      </body>
    </html>
  );
}}
"""


def _providers(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

import {{ QueryClient, QueryClientProvider }} from "@tanstack/react-query";
import {{ useState }} from "react";

export function Providers({{ children }}: {{ children: React.ReactNode }}) {{
  const [queryClient] = useState(
    () =>
      new QueryClient({{
        defaultOptions: {{
          queries: {{
            staleTime: 60 * 1000,
            retry: 1,
          }},
        }},
      }}),
  );

  return (
    <QueryClientProvider client={{queryClient}}>
      {{children}}
    </QueryClientProvider>
  );
}}
"""


# ── Auth layout + pages ───────────────────────────────────────────────


def _auth_layout(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
export default function AuthLayout({{
  children,
}}: {{
  children: React.ReactNode;
}}) {{
  return (
    <div className="flex min-h-screen items-center justify-center bg-muted/40 p-4">
      <div className="w-full max-w-md">{{children}}</div>
    </div>
  );
}}
"""


def _landing_page(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
import {{ redirect }} from "next/navigation";

export default function LandingPage() {{
  redirect("/login");
}}
"""


def _login_page(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

import {{ useState }} from "react";
import {{ useRouter }} from "next/navigation";
import {{ Button }} from "@/components/ui/button";
import {{ Input }} from "@/components/ui/input";
import {{ Label }} from "@/components/ui/label";
import {{ Card, CardContent, CardDescription, CardHeader, CardTitle }} from "@/components/ui/card";
import * as authApi from "@/generated/api/auth";

export default function LoginPage() {{
  const router = useRouter();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  async function handleSubmit(e: React.FormEvent) {{
    e.preventDefault();
    setError(null);
    setLoading(true);
    try {{
      await authApi.login_api_auth_login_post({{ email, password }});
      router.push("/profile");
    }} catch (err: unknown) {{
      setError(err instanceof Error ? err.message : "Login failed");
    }} finally {{
      setLoading(false);
    }}
  }}

  return (
    <Card>
      <CardHeader className="text-center">
        <CardTitle className="text-2xl">{ir.marketplace.name}</CardTitle>
        <CardDescription>Sign in to your account</CardDescription>
      </CardHeader>
      <CardContent>
        <form onSubmit={{handleSubmit}} className="space-y-4">
          {{error && (
            <div className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">
              {{error}}
            </div>
          )}}
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input
              id="email"
              type="email"
              value={{email}}
              onChange={{(e) => setEmail(e.target.value)}}
              required
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">Password</Label>
            <Input
              id="password"
              type="password"
              value={{password}}
              onChange={{(e) => setPassword(e.target.value)}}
              required
            />
          </div>
          <Button type="submit" className="w-full" disabled={{loading}}>
            {{loading ? "Signing in..." : "Sign In"}}
          </Button>
        </form>
      </CardContent>
    </Card>
  );
}}
"""


def _signup_page(ir: FrontendIR) -> str:
    type_options = "\n".join(
        f'            <option value="{e.slug}">{e.name}</option>'
        for e in ir.entities
    )
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

import {{ useState }} from "react";
import {{ useRouter }} from "next/navigation";
import {{ Button }} from "@/components/ui/button";
import {{ Input }} from "@/components/ui/input";
import {{ Label }} from "@/components/ui/label";
import {{ Card, CardContent, CardDescription, CardHeader, CardTitle }} from "@/components/ui/card";
import * as authApi from "@/generated/api/auth";

export default function SignupPage() {{
  const router = useRouter();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [participantType, setParticipantType] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  async function handleSubmit(e: React.FormEvent) {{
    e.preventDefault();
    setError(null);
    setLoading(true);
    try {{
      await authApi.signup_api_auth_signup_post({{
        email,
        password,
        participant_type: participantType,
      }});
      router.push("/profile");
    }} catch (err: unknown) {{
      setError(err instanceof Error ? err.message : "Signup failed");
    }} finally {{
      setLoading(false);
    }}
  }}

  return (
    <Card>
      <CardHeader className="text-center">
        <CardTitle className="text-2xl">Create Account</CardTitle>
        <CardDescription>Join {ir.marketplace.name}</CardDescription>
      </CardHeader>
      <CardContent>
        <form onSubmit={{handleSubmit}} className="space-y-4">
          {{error && (
            <div className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">
              {{error}}
            </div>
          )}}
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input
              id="email"
              type="email"
              value={{email}}
              onChange={{(e) => setEmail(e.target.value)}}
              required
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">Password</Label>
            <Input
              id="password"
              type="password"
              value={{password}}
              onChange={{(e) => setPassword(e.target.value)}}
              required
              minLength={{8}}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="type">I am a...</Label>
            <select
              id="type"
              className="w-full rounded-md border border-input bg-background px-3 py-2"
              value={{participantType}}
              onChange={{(e) => setParticipantType(e.target.value)}}
              required
            >
              <option value="">Select type</option>
{type_options}
            </select>
          </div>
          <Button type="submit" className="w-full" disabled={{loading}}>
            {{loading ? "Creating account..." : "Create Account"}}
          </Button>
        </form>
      </CardContent>
    </Card>
  );
}}
"""


# ── Dashboard layout + pages ──────────────────────────────────────────


def _dashboard_layout(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
import {{ AppSidebar }} from "@/components/layouts/app-sidebar";
import {{ Header }} from "@/components/layouts/header";

export default function DashboardLayout({{
  children,
}}: {{
  children: React.ReactNode;
}}) {{
  return (
    <div className="flex min-h-screen">
      <AppSidebar />
      <div className="flex flex-1 flex-col">
        <Header />
        <main className="flex-1 p-6">{{children}}</main>
      </div>
    </div>
  );
}}
"""


def _dashboard_page(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
export default function DashboardPage() {{
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Dashboard</h1>
        <p className="text-muted-foreground">
          Welcome to {ir.marketplace.name}
        </p>
      </div>
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        <div className="rounded-lg border bg-card p-6">
          <h3 className="text-sm font-medium text-muted-foreground">Profile Status</h3>
          <p className="mt-2 text-2xl font-bold">—</p>
        </div>
        <div className="rounded-lg border bg-card p-6">
          <h3 className="text-sm font-medium text-muted-foreground">Messages</h3>
          <p className="mt-2 text-2xl font-bold">—</p>
        </div>
        <div className="rounded-lg border bg-card p-6">
          <h3 className="text-sm font-medium text-muted-foreground">Notifications</h3>
          <p className="mt-2 text-2xl font-bold">—</p>
        </div>
      </div>
    </div>
  );
}}
"""


# ── Profile pages ─────────────────────────────────────────────────────


def _profile_view_page(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

import {{ useRouter }} from "next/navigation";
import {{ Button }} from "@/components/ui/button";
import {{ Card, CardContent, CardHeader, CardTitle }} from "@/components/ui/card";

export default function ProfileViewPage() {{
  const router = useRouter();

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">My Profile</h1>
          <p className="text-muted-foreground">View your profile information</p>
        </div>
        <Button onClick={{() => router.push("/profile/edit")}}>Edit Profile</Button>
      </div>
      <Card>
        <CardHeader>
          <CardTitle>Profile Details</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-muted-foreground">
            Profile data will appear here once loaded.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}}
"""


def _profile_edit_page(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

import {{ ProfileForm }} from "@/components/forms/profile-form";

export default function ProfileEditPage() {{
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Edit Profile</h1>
        <p className="text-muted-foreground">Update your profile information</p>
      </div>
      <ProfileForm />
    </div>
  );
}}
"""


def _profile_detail_page(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

import {{ use }} from "react";
import {{ Card, CardContent, CardHeader, CardTitle }} from "@/components/ui/card";

export default function ProfileDetailPage({{
  params,
}}: {{
  params: Promise<{{ id: string }}>
}}) {{
  const {{ id }} = use(params);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Profile</h1>
        <p className="text-muted-foreground">Viewing profile {{id}}</p>
      </div>
      <Card>
        <CardHeader>
          <CardTitle>Profile Information</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-muted-foreground">
            Profile details will appear here.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}}
"""


# ── Search page ───────────────────────────────────────────────────────


def _search_page(ir: FrontendIR) -> str:
    searchable = ", ".join(
        slug_to_pascal(s) + "s" for s in ir.discovery.searchable_types
    )
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

import {{ useState }} from "react";
import {{ Button }} from "@/components/ui/button";
import {{ Input }} from "@/components/ui/input";
import {{ Card, CardContent, CardHeader, CardTitle }} from "@/components/ui/card";
import {{ SearchFilters }} from "@/components/shared/search-filters";

export default function SearchPage() {{
  const [query, setQuery] = useState("");

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Search</h1>
        <p className="text-muted-foreground">Find {searchable}</p>
      </div>
      <div className="flex gap-4">
        <Input
          placeholder="Search..."
          value={{query}}
          onChange={{(e) => setQuery(e.target.value)}}
          className="max-w-md"
        />
        <Button>Search</Button>
      </div>
      <SearchFilters />
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        <Card>
          <CardContent className="pt-6">
            <p className="text-center text-muted-foreground">
              Search results will appear here.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}}
"""


# ── Conversation pages ────────────────────────────────────────────────


def _conversations_page(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

import {{ Card, CardContent, CardHeader, CardTitle }} from "@/components/ui/card";
import {{ Button }} from "@/components/ui/button";

export default function ConversationsPage() {{
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Messages</h1>
          <p className="text-muted-foreground">Your conversations</p>
        </div>
        <Button>New Conversation</Button>
      </div>
      <Card>
        <CardContent className="pt-6">
          <p className="text-center text-muted-foreground">
            No conversations yet.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}}
"""


def _conversation_detail_page(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

import {{ use }} from "react";
import {{ Card, CardContent, CardHeader, CardTitle }} from "@/components/ui/card";
import {{ Input }} from "@/components/ui/input";
import {{ Button }} from "@/components/ui/button";

export default function ConversationDetailPage({{
  params,
}}: {{
  params: Promise<{{ id: string }}>
}}) {{
  const {{ id }} = use(params);

  return (
    <div className="flex h-[calc(100vh-8rem)] flex-col">
      <div className="border-b p-4">
        <h1 className="text-lg font-semibold">Conversation</h1>
        <p className="text-sm text-muted-foreground">ID: {{id}}</p>
      </div>
      <div className="flex-1 overflow-y-auto p-4">
        <p className="text-center text-muted-foreground">Messages will appear here.</p>
      </div>
      <div className="border-t p-4">
        <div className="flex gap-2">
          <Input placeholder="Type a message..." className="flex-1" />
          <Button>Send</Button>
        </div>
      </div>
    </div>
  );
}}
"""


# ── Notifications page ────────────────────────────────────────────────


def _notifications_page(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

import {{ Card, CardContent }} from "@/components/ui/card";

export default function NotificationsPage() {{
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Notifications</h1>
        <p className="text-muted-foreground">Stay up to date</p>
      </div>
      <Card>
        <CardContent className="pt-6">
          <p className="text-center text-muted-foreground">
            No notifications yet.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}}
"""


# ── Registration page ─────────────────────────────────────────────────


def _register_page(ir: FrontendIR) -> str:
    return f"""\
{_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)}
"use client";

import {{ use }} from "react";
import {{ Card, CardContent, CardHeader, CardTitle, CardDescription }} from "@/components/ui/card";
import {{ Button }} from "@/components/ui/button";
import {{ Input }} from "@/components/ui/input";
import {{ Label }} from "@/components/ui/label";

export default function RegisterPage({{
  params,
}}: {{
  params: Promise<{{ type: string }}>
}}) {{
  const {{ type }} = use(params);

  return (
    <div className="flex min-h-screen items-center justify-center bg-muted/40 p-4">
      <Card className="w-full max-w-lg">
        <CardHeader className="text-center">
          <CardTitle className="text-2xl">Register as {{type}}</CardTitle>
          <CardDescription>
            Submit your application to join {ir.marketplace.name}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input id="email" type="email" required />
            </div>
            <Button type="submit" className="w-full">
              Submit Application
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}}
"""
