"""Generate Zod validation schemas from the FrontendIR.

Emits ``src/generated/schemas.ts`` with per-entity draft field schemas
that stay in sync with the TypeScript types.
"""

from __future__ import annotations

from ..ir import EntityIR, FieldIR, FrontendIR
from ..naming import slug_to_camel, slug_to_pascal

_HEADER = """\
// AUTO-GENERATED by Cosolvent Frontend Compiler v{version}
// spec_hash: {hash}
// DO NOT EDIT — changes will be overwritten on next compile

import {{ z }} from "zod";
"""


def emit_schemas(ir: FrontendIR) -> dict[str, str]:
    lines: list[str] = [_HEADER.format(version=ir.generator_version, hash=ir.spec_hash)]

    for entity in ir.entities:
        lines.append(_entity_schemas(entity))

    lines.append(_auth_schemas())
    lines.append(_conversation_schemas())
    lines.append(_search_schemas())

    return {"src/generated/schemas.ts": "\n".join(lines) + "\n"}


def _entity_schemas(entity: EntityIR) -> str:
    camel = slug_to_camel(entity.slug)
    pascal = slug_to_pascal(entity.slug)
    lines: list[str] = []
    lines.append(f"\n// ── {pascal} ─────────────────────────────────────────────────")
    lines.append("")

    # Draft fields schema
    lines.append(f"export const {camel}DraftFieldsSchema = z.object({{")
    for section in entity.sections:
        for field in section.fields:
            lines.append(f"  {field.name}: {_zod_field(field)},")
    lines.append("});")
    lines.append("")

    # Draft update schema (partial)
    lines.append(f"export const {camel}DraftUpdateSchema = z.object({{")
    lines.append(f"  fields: {camel}DraftFieldsSchema.partial(),")
    lines.append("});")
    lines.append("")

    # Inferred types
    lines.append(
        f"export type {pascal}DraftFieldsSchema = z.infer<typeof {camel}DraftFieldsSchema>;"
    )
    lines.append(
        f"export type {pascal}DraftUpdateSchema = z.infer<typeof {camel}DraftUpdateSchema>;"
    )

    return "\n".join(lines)


def _zod_field(field: FieldIR) -> str:
    """Map a FieldIR to a Zod schema expression."""
    base: str

    if field.field_type in ("select",) and field.options:
        opts = ", ".join(f'"{o}"' for o in field.options)
        base = f"z.enum([{opts}])"
    elif field.field_type == "multi_select" and field.options:
        opts = ", ".join(f'"{o}"' for o in field.options)
        base = f"z.array(z.enum([{opts}]))"
        if field.required:
            base += f'.min(1, "{field.label} is required")'
    elif field.field_type == "number":
        base = "z.number()"
    elif field.field_type == "date":
        base = "z.string()"
    elif field.field_type in ("file", "files"):
        if field.field_type == "files":
            base = "z.array(z.string())"
        else:
            base = "z.string()"
    else:
        base = "z.string()"
        if field.required:
            base += f'.min(1, "{field.label} is required")'

    if not field.required:
        base += ".optional()"

    return base


def _auth_schemas() -> str:
    return """
// ── Auth ─────────────────────────────────────────────────────────────

export const loginSchema = z.object({
  email: z.string().email("Valid email is required"),
  password: z.string().min(1, "Password is required"),
});

export const signupSchema = z.object({
  email: z.string().email("Valid email is required"),
  password: z.string().min(8, "Password must be at least 8 characters"),
  participant_type: z.string().min(1, "Participant type is required"),
  display_name: z.string().optional(),
});

export type LoginSchema = z.infer<typeof loginSchema>;
export type SignupSchema = z.infer<typeof signupSchema>;
"""


def _conversation_schemas() -> str:
    return """
// ── Conversations ────────────────────────────────────────────────────

export const createConversationSchema = z.object({
  recipient_id: z.string().min(1, "Recipient is required"),
  subject: z.string().optional(),
  initial_message: z.string().optional(),
});

export const sendMessageSchema = z.object({
  content: z.string().min(1, "Message cannot be empty"),
});

export type CreateConversationSchema = z.infer<typeof createConversationSchema>;
export type SendMessageSchema = z.infer<typeof sendMessageSchema>;
"""


def _search_schemas() -> str:
    return """
// ── Search ───────────────────────────────────────────────────────────

export const searchSchema = z.object({
  query: z.string().optional(),
  filters: z.record(z.union([z.string(), z.array(z.string())])).optional(),
  skip: z.number().int().min(0).optional(),
  limit: z.number().int().min(1).max(100).optional(),
});

export type SearchSchema = z.infer<typeof searchSchema>;
"""
