"""Generate TypeScript type definitions from the FrontendIR.

Emits ``src/generated/types.ts`` containing:
- Per-entity draft field interfaces
- Per-entity draft update request / profile response interfaces
- Shared enums and utility types
- All OpenAPI-derived schema interfaces
"""

from __future__ import annotations

import re

from ..ir import EntityIR, FrontendIR, SchemaIR
from ..naming import slug_to_pascal

_DECL_RE = re.compile(r"^export (?:interface|type|const|enum) (\w+)", re.MULTILINE)

_HEADER = """\
// AUTO-GENERATED by Cosolvent Frontend Compiler v{version}
// spec_hash: {hash}
// DO NOT EDIT — changes will be overwritten on next compile
"""


def emit_types(ir: FrontendIR) -> dict[str, str]:
    """Return ``{relative_path: content}`` for type definitions."""
    lines: list[str] = []
    lines.append(_HEADER.format(version=ir.generator_version, hash=ir.spec_hash))

    lines.append(_shared_types())

    for entity in ir.entities:
        lines.append(_entity_types(entity))

    lines.append(_auth_types())
    lines.append(_conversation_types())
    lines.append(_notification_types())
    lines.append(_search_types())
    lines.append(_file_types())

    # Names already declared by the entity/shared blocks above. The OpenAPI components
    # include the same profile schemas (e.g. SellerProfileResponse, SellerCountryOption)
    # that the entity types emit, so emitting both produces duplicate identifiers and
    # conflicting property types. Skip any OpenAPI schema whose name is already declared.
    emitted_names = set(_DECL_RE.findall("\n".join(lines)))
    for schema in ir.schemas:
        if schema.name in emitted_names:
            continue
        emitted_names.add(schema.name)
        lines.append(_openapi_schema_interface(schema))

    return {"src/generated/types.ts": "\n".join(lines) + "\n"}


def _shared_types() -> str:
    return """\

// ── Shared types ─────────────────────────────────────────────────────

export type ProfileStatus = "draft" | "submitted" | "approved" | "rejected";
export type ParticipantRole = "supply" | "demand" | "facilitator";

export interface PaginationParams {
  skip?: number;
  limit?: number;
}

export interface ApiErrorBody {
  detail: string;
}
"""


def _entity_types(entity: EntityIR) -> str:
    pascal = slug_to_pascal(entity.slug)
    lines: list[str] = []
    lines.append(f"\n// ── {pascal} ─────────────────────────────────────────────────")
    lines.append("")

    # Draft fields interface
    lines.append(f"export interface {pascal}DraftFields {{")
    for section in entity.sections:
        for field in section.fields:
            optional = "" if field.required else "?"
            lines.append(f"  {field.name}{optional}: {field.ts_type};")
    lines.append("}")
    lines.append("")

    # Draft update request
    lines.append(f"export interface {pascal}DraftUpdateRequest {{")
    lines.append(f"  fields: Partial<{pascal}DraftFields>;")
    lines.append("}")
    lines.append("")

    # Profile response
    lines.append(f"export interface {pascal}ProfileResponse {{")
    lines.append("  id: string;")
    lines.append("  user_id: string;")
    lines.append(f'  participant_type: "{entity.slug}";')
    lines.append("  status: ProfileStatus;")
    lines.append(f"  fields: {pascal}DraftFields;")
    lines.append("  completeness: number;")
    lines.append("  created_at: string;")
    lines.append("  updated_at: string;")
    lines.append("}")

    # Field options as const arrays (for selects)
    for section in entity.sections:
        for field in section.fields:
            if field.options:
                const_name = f"{pascal.upper()}_{field.name.upper()}_OPTIONS"
                opts = ", ".join(f'"{o}"' for o in field.options)
                lines.append("")
                lines.append(f"export const {const_name} = [{opts}] as const;")
                lines.append(
                    f"export type {pascal}{slug_to_pascal(field.name)}Option = "
                    f"(typeof {const_name})[number];"
                )

    return "\n".join(lines)


def _auth_types() -> str:
    return """
// ── Auth ─────────────────────────────────────────────────────────────

export interface LoginRequest {
  email: string;
  password: string;
}

export interface SignupRequest {
  email: string;
  password: string;
  participant_type: string;
  display_name?: string;
}

export interface AuthResponse {
  user_id: string;
  email: string;
  role: string;
  participant_type: string | null;
}

export interface UserResponse {
  id: string;
  email: string;
  role: string;
  participant_type: string | null;
  is_active: boolean;
  display_name: string | null;
  created_at: string;
}
"""


def _conversation_types() -> str:
    return """
// ── Conversations ────────────────────────────────────────────────────

export interface CreateConversationRequest {
  recipient_id: string;
  subject?: string;
  initial_message?: string;
}

export interface SendMessageRequest {
  content: string;
}

export interface EditMessageRequest {
  content: string;
}

export interface ConversationResponse {
  id: string;
  participants: string[];
  status: string;
  subject: string | null;
  created_at: string;
  updated_at: string;
}

export interface MessageResponse {
  id: string;
  conversation_id: string;
  sender_id: string;
  content: string;
  created_at: string;
  updated_at: string | null;
}
"""


def _notification_types() -> str:
    return """
// ── Notifications ────────────────────────────────────────────────────

export interface NotificationResponse {
  id: string;
  user_id: string;
  type: string;
  title: string;
  body: string | null;
  read: boolean;
  data: Record<string, unknown> | null;
  created_at: string;
}
"""


def _search_types() -> str:
    return """
// ── Search / Discovery ───────────────────────────────────────────────

export interface SearchRequest {
  query?: string;
  filters?: Record<string, string | string[]>;
  skip?: number;
  limit?: number;
}

export interface SearchResultItem {
  id: string;
  participant_type: string;
  fields: Record<string, unknown>;
  score?: number;
}

export interface SearchResponse {
  results: SearchResultItem[];
  total: number;
}
"""


def _file_types() -> str:
    return """
// ── Files ────────────────────────────────────────────────────────────

export interface FileResponse {
  id: string;
  filename: string;
  content_type: string;
  size: number;
  privacy: string;
  url?: string;
  created_at: string;
}
"""


def _openapi_schema_interface(schema: SchemaIR) -> str:
    if not schema.properties:
        return f"\nexport type {schema.name} = Record<string, unknown>;\n"

    lines: list[str] = [f"\nexport interface {schema.name} {{"]
    for prop in schema.properties:
        optional = "" if prop.required else "?"
        nullable_suffix = " | null" if prop.nullable else ""
        lines.append(f"  {prop.name}{optional}: {prop.ts_type}{nullable_suffix};")
    lines.append("}")
    return "\n".join(lines)
