"""End-to-end ingest of a real ClientSynth population export (GAP-10 / GAP-9).

The fixture is genuine output: records generated by ClientSynth against the
published `producer` profile schema, mapped by its population exporter and
signed by its TypeScript watermark implementation. Nothing in it was produced by
this codebase, so the test exercises the actual cross-system contract —
canonicalisation, watermark verification, schema validation, upsert and indexing
— rather than a Python-signed stand-in.

Embeddings are stubbed with a deterministic content-derived vector so the full
path runs against a real migrated database without an embedding provider.

Gated by RUN_INTEGRATION.

Regenerate the fixture with:
    npx tsx scripts/e2e-generate-aligned.ts --target-schema producer.schema.json --count 6
    npx tsx scripts/export-population.ts --job <id> -o population-e2e.json \
        --target-schema producer.schema.json
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from unittest.mock import AsyncMock, patch

import pytest

from app.core.database import close_db, connect_db, get_collection
from app.core.marketplace_config import load_marketplace_config
from app.modules.discovery import vector_service
from app.modules.population.service import import_population
from tests.e2e.helpers import require_mode

FIXTURES = Path(__file__).parent.parent / "test_config"
POPULATION_FILE = Path(__file__).parent.parent / "fixtures" / "clientsynth_population.json"

# The secret the fixture was signed with. Must match ClientSynth's
# SYNTHETIC_WATERMARK_SECRET at export time.
SECRET = "e2e-shared-secret"
DIM = 1536


def _load_records() -> list[dict]:
    payload = json.loads(POPULATION_FILE.read_text(encoding="utf-8"))
    return payload["records"]


def _vec_for(text: str) -> list[float]:
    digest = hashlib.sha256(text.encode("utf-8")).digest()
    base = [b / 255.0 for b in digest]
    v = (base * (DIM // len(base) + 1))[:DIM]
    norm = sum(x * x for x in v) ** 0.5 or 1.0
    return [x / norm for x in v]


async def _cleanup(records: list[dict]) -> None:
    for r in records:
        await get_collection("profiles").delete_one({"external_id": r["external_id"]})
        await get_collection("users").delete_one({"external_id": r["external_id"]})


def _strip_watermarks(records: list[dict]) -> list[dict]:
    return [{k: v for k, v in r.items() if k != "_watermark"} for r in records]


def _tamper(records: list[dict]) -> list[dict]:
    """Change a signed field without touching the signature."""
    out = json.loads(json.dumps(records))
    out[0]["fields"]["farm_name"] = "ATTACKER INJECTED FARM"
    return out


@pytest.mark.integration
@pytest.mark.asyncio
async def test_clientsynth_population_ingest_e2e():
    require_mode("RUN_INTEGRATION")

    cfg = load_marketplace_config(FIXTURES / "agriculture.yaml")
    records = _load_records()
    assert len(records) >= 2, "fixture should carry a meaningful population"

    await connect_db()
    try:
        await _cleanup(records)

        with patch(
            "app.modules.discovery.indexer.get_embedding",
            new=AsyncMock(side_effect=lambda text: _vec_for(text)),
        ):
            # 1. ClientSynth's watermark verifies here, and every record passes
            #    the marketplace profile schema.
            res = await import_population(cfg, records, mode="demo", secret=SECRET, do_index=True)
            assert res.rejected_watermark == 0, res.errors
            assert res.skipped_invalid == 0, res.errors
            assert res.loaded == len(records)
            assert res.indexed == len(records)

            # 2. Values arrive with the types the schema declares, not as the
            #    strings structured output would otherwise produce.
            profile = await get_collection("profiles").find_one({"external_id": records[0]["external_id"]})
            assert profile is not None
            assert profile["is_synthetic"] is True
            assert profile["participant_type"] == "producer"
            assert isinstance(profile["fields"]["primary_crops"], list)
            assert profile["fields"]["country"] in {"Canada", "USA"}

            # 3. Each synthetic profile owns a synthetic user.
            user = await get_collection("users").find_one({"external_id": records[0]["external_id"]})
            assert user is not None and user["is_synthetic"] is True

            # 4. The indexed vector is retrievable through the same search
            #    discovery and matching use.
            fields = records[0]["fields"]
            crops = " ".join(fields.get("primary_crops", []))
            hits = await vector_service.find_similar_profiles(
                embedding=_vec_for(f"[producer] {fields['farm_name']} {crops}"),
                participant_types=["producer"],
                exclude_profile_ids=[],
                min_score=0.0,
                limit=20,
            )
            assert any(h["id"] == str(profile["_id"]) for h in hits)

            # 5. Re-importing the same export upserts in place — the population
            #    does not double on a repeated run.
            again = await import_population(cfg, records, mode="demo", secret=SECRET, do_index=True)
            assert again.loaded == 0
            assert again.updated == len(records)

        # 6. Tampering with a signed field is detected.
        tampered = await import_population(cfg, _tamper(records), mode="demo", secret=SECRET, do_index=False)
        assert tampered.rejected_watermark == 1, tampered.errors

        # 7. Demo mode requires a watermark.
        unmarked = await import_population(
            cfg, _strip_watermarks(records), mode="demo", secret=SECRET, do_index=False
        )
        assert unmarked.rejected_watermark == len(records)
        assert unmarked.loaded == 0

        # 8. A secret mismatch between the two systems rejects everything rather
        #    than silently trusting the marker.
        wrong_secret = await import_population(
            cfg, records, mode="demo", secret="not-the-shared-secret", do_index=False
        )
        assert wrong_secret.rejected_watermark == len(records)

        # 9. Production rejects watermarked (synthetic) data — the clean cutover.
        production = await import_population(cfg, records, mode="production", secret=SECRET, do_index=False)
        assert production.rejected_watermark == len(records)
        assert production.loaded == 0
    finally:
        await _cleanup(records)
        await close_db()
