const HELP_ENTRIES = [
  {
    pattern: "quick_answers.readiness",
    label: "Team Readiness",
    description: "Applies default policy intensity across onboarding controls.",
    whyItMatters: "This can quickly increase or reduce manual review workload.",
    example: "review-heavy turns on stricter approval defaults.",
    recommendedDefault: "lean for first launch.",
    riskLevel: "medium",
  },
  {
    pattern: "quick_answers.launch_style",
    label: "Launch Style",
    description: "Applies speed-first or quality-first onboarding defaults.",
    whyItMatters: "Affects how quickly users are activated and how curated listings are.",
    example: "curated enables stronger supply-side review defaults.",
    recommendedDefault: "fast for MVP validation.",
    riskLevel: "medium",
  },
  {
    pattern: "marketplace.name",
    label: "Marketplace Name",
    description: "Public brand name for your marketplace.",
    whyItMatters: "Appears in generated API docs and setup interfaces.",
    example: "AgriExchange",
    recommendedDefault: "Short brand-style name.",
    riskLevel: "low",
  },
  {
    pattern: "marketplace.industry",
    label: "Industry",
    description: "Vertical or category your marketplace serves.",
    whyItMatters: "Used for operator context and export metadata.",
    example: "Specialty Agriculture",
    recommendedDefault: "One clear vertical phrase.",
    riskLevel: "low",
  },
  {
    pattern: "marketplace.description",
    label: "Marketplace Description",
    description: "Short summary of your marketplace purpose.",
    whyItMatters: "Used in docs and internal/admin understanding of configuration intent.",
    example: "Connect verified producers with global buyers.",
    recommendedDefault: "One sentence in plain language.",
    riskLevel: "low",
  },
  {
    pattern: "participant_types.*.name",
    label: "Role Name",
    description: "Human-readable participant role name.",
    whyItMatters: "Appears throughout onboarding and role-specific UX surfaces.",
    example: "Producer",
    recommendedDefault: "Singular, title case role name.",
    riskLevel: "medium",
  },
  {
    pattern: "participant_types.*.slug",
    label: "Role Slug",
    description: "Stable machine identifier used in generated endpoint aliases and config references.",
    whyItMatters: "Slug changes are breaking because they alter generated API routes and references.",
    example: "producer",
    recommendedDefault: "Lowercase with underscores.",
    riskLevel: "high",
  },
  {
    pattern: "participant_types.*.role",
    label: "Role Type",
    description: "Classifies whether this role supplies, demands, or facilitates.",
    whyItMatters: "Guides policy defaults and operator expectations.",
    example: "supply for listing-side participants.",
    recommendedDefault: "Match real business role behavior.",
    riskLevel: "medium",
  },
  {
    pattern: "participant_types.*.permissions.can_list",
    label: "Can List",
    description: "Allows this role to publish listings or profile entries.",
    whyItMatters: "Controls who contributes supply-side inventory/profile content.",
    example: "Producer can list; buyer cannot.",
    recommendedDefault: "Enable only for supply-side roles.",
    riskLevel: "medium",
  },
  {
    pattern: "participant_types.*.permissions.can_search",
    label: "Can Search",
    description: "Allows this role to run discovery searches.",
    whyItMatters: "At least one role must be able to search or discovery is unusable.",
    example: "Buyer role can search producer profiles.",
    recommendedDefault: "Enable for demand-side roles.",
    riskLevel: "medium",
  },
  {
    pattern: "participant_types.*.permissions.can_initiate_conversation",
    label: "Can Initiate Conversation",
    description: "Allows this role to start conversations with other users.",
    whyItMatters: "Controls outbound communication permissions and demand pressure.",
    example: "Buyers can initiate contact.",
    recommendedDefault: "Enable only for intended initiator roles.",
    riskLevel: "medium",
  },
  {
    pattern: "participant_types.*.permissions.can_receive_conversation",
    label: "Can Receive Conversation",
    description: "Allows this role to receive inbound conversations.",
    whyItMatters: "If disabled, users in this role cannot be contacted.",
    example: "Suppliers can receive buyer outreach.",
    recommendedDefault: "Enable for roles expected to be contacted.",
    riskLevel: "medium",
  },
  {
    pattern: "participant_types.*.permissions.can_share_private_assets",
    label: "Can Share Private Assets",
    description: "Allows private files/documents to be shared.",
    whyItMatters: "Expands data-sharing surface and compliance obligations.",
    example: "Vetted suppliers can share private certifications.",
    recommendedDefault: "Enable only where needed.",
    riskLevel: "high",
  },
  {
    pattern: "participant_types.*.permissions.requires_onboarding",
    label: "Requires Onboarding",
    description: "Requires users in this role to complete onboarding before full access.",
    whyItMatters: "Defines the minimum trust gate before runtime actions.",
    example: "Suppliers must complete onboarding first.",
    recommendedDefault: "Enabled for all production roles.",
    riskLevel: "high",
  },
  {
    pattern: "participant_types.*.permissions.requires_approval",
    label: "Requires Approval",
    description: "Requires explicit approval before role activation.",
    whyItMatters: "Adds moderation quality but increases ops latency.",
    example: "High-risk roles require admin approval.",
    recommendedDefault: "Enable for supply-side roles.",
    riskLevel: "high",
  },
  {
    pattern: "participant_types.*.permissions.visible_in_search",
    label: "Visible in Search",
    description: "Makes role profiles discoverable in search results.",
    whyItMatters: "At least one role must be visible for discovery to return useful results.",
    example: "Producer profiles visible in search.",
    recommendedDefault: "Enable on listing/provider roles.",
    riskLevel: "medium",
  },
  {
    pattern: "onboarding.*.requires_approval",
    label: "Onboarding Requires Approval",
    description: "Submitted onboarding drafts require admin action.",
    whyItMatters: "Controls who can self-activate versus moderated activation.",
    example: "Producer drafts require review.",
    recommendedDefault: "Enable for high-risk listing roles.",
    riskLevel: "high",
  },
  {
    pattern: "onboarding.*.approval_type",
    label: "Approval Type",
    description: "Determines manual or automatic decision mode for onboarding.",
    whyItMatters: "Directly changes activation speed and risk posture.",
    example: "manual for providers, auto for buyers.",
    recommendedDefault: "manual where trust screening is needed.",
    riskLevel: "high",
  },
  {
    pattern: "onboarding.*.profile_completeness_threshold",
    label: "Profile Completeness Threshold",
    description: "Minimum completion percentage required before submission.",
    whyItMatters: "Higher thresholds improve listing quality and data completeness.",
    example: "80 for providers, 100 for buyers.",
    recommendedDefault: "80 to 100.",
    riskLevel: "medium",
  },
  {
    pattern: "onboarding.*.document_upload_required",
    label: "Document Upload Required",
    description: "Requires documents as part of onboarding for this role.",
    whyItMatters: "Adds verification signals and operational review requirements.",
    example: "Suppliers must upload certification docs.",
    recommendedDefault: "Enable for trust-sensitive roles.",
    riskLevel: "high",
  },
  {
    pattern: "onboarding.*.ai_extraction_enabled",
    label: "AI Extraction Enabled",
    description: "Allows AI to extract structured data from uploaded documents.",
    whyItMatters: "Can accelerate operations, but needs quality checks.",
    example: "Extract certification fields from PDFs.",
    recommendedDefault: "Enable after extraction quality is validated.",
    riskLevel: "medium",
  },
  {
    pattern: "onboarding.*.ai_profile_generation",
    label: "AI Profile Generation",
    description: "Allows AI-generated profile draft content.",
    whyItMatters: "Improves speed but may require moderation for correctness.",
    example: "Generate draft company summary.",
    recommendedDefault: "Enable with human review.",
    riskLevel: "medium",
  },
  {
    pattern: "onboarding.*.welcome_email_on_approval",
    label: "Welcome Email On Approval",
    description: "Sends a welcome message when approval completes.",
    whyItMatters: "Improves activation conversion and onboarding clarity.",
    example: "Approved supplier receives onboarding next steps.",
    recommendedDefault: "Enabled.",
    riskLevel: "low",
  },
  {
    pattern: "communication.conversation_rules.*.initiator",
    label: "Conversation Initiator",
    description: "Role allowed to start conversations in this rule.",
    whyItMatters: "Controls demand pressure and outreach direction.",
    example: "Buyer initiates conversation with supplier.",
    recommendedDefault: "Start with demand-side initiators.",
    riskLevel: "medium",
  },
  {
    pattern: "communication.conversation_rules.*.receiver",
    label: "Conversation Receiver",
    description: "Role that can receive conversations in this rule.",
    whyItMatters: "Defines who is discoverable for outreach.",
    example: "Supplier receives buyer requests.",
    recommendedDefault: "Supply-side receivers for MVP.",
    riskLevel: "medium",
  },
  {
    pattern: "communication.conversation_rules.*.requires_approval",
    label: "Conversation Requires Approval",
    description: "Whether this conversation path requires approval.",
    whyItMatters: "Balances trust/safety and messaging friction.",
    example: "First contact requires approval.",
    recommendedDefault: "Enabled until abuse risk is understood.",
    riskLevel: "high",
  },
  {
    pattern: "discovery.searchable_types",
    label: "Searchable Roles",
    description: "Roles included in discovery search result sets.",
    whyItMatters: "Defines the target population for search queries.",
    example: "Only suppliers are searchable.",
    recommendedDefault: "Include your primary listing role.",
    riskLevel: "medium",
  },
  {
    pattern: "discovery.filter_fields",
    label: "Filter Fields",
    description: "Comma-separated profile fields exposed as filters.",
    whyItMatters: "Impacts result quality, privacy posture, and search UX.",
    example: "country, certifications",
    recommendedDefault: "Start with high-signal public attributes only.",
    riskLevel: "high",
  },
  {
    pattern: "discovery.result_visibility.anonymous",
    label: "Anonymous Result Visibility",
    description: "Max visibility tier for unauthenticated users.",
    whyItMatters: "Controls public data exposure.",
    example: "public only.",
    recommendedDefault: "public.",
    riskLevel: "high",
  },
  {
    pattern: "discovery.result_visibility.authenticated",
    label: "Authenticated Result Visibility",
    description: "Max visibility tier for authenticated users.",
    whyItMatters: "Controls whether protected fields are visible after sign-in.",
    example: "protected for signed-in users.",
    recommendedDefault: "protected.",
    riskLevel: "high",
  },
  {
    pattern: "discovery.access.anonymous_search_enabled",
    label: "Anonymous Search Access",
    description: "Allows unauthenticated visitors to execute search endpoints.",
    whyItMatters: "Changes public surface area and traffic profile significantly.",
    example: "Enabled for directory-style public marketplaces.",
    recommendedDefault: "Disabled unless intentionally public.",
    riskLevel: "high",
  },
  {
    pattern: "discovery.access.anonymous_filter_mode",
    label: "Anonymous Filter Mode",
    description: "Controls which filters anonymous users can apply.",
    whyItMatters: "Prevents inference risks from sensitive filters.",
    example: "public_only",
    recommendedDefault: "public_only.",
    riskLevel: "high",
  },
  {
    pattern: "discovery.ai.vector_search_enabled",
    label: "Vector Search Enabled",
    description: "Enables vector similarity retrieval for discovery.",
    whyItMatters: "Impacts retrieval quality and model dependency.",
    example: "Semantic ranking for sparse keyword queries.",
    recommendedDefault: "Enabled if embeddings pipeline is healthy.",
    riskLevel: "medium",
  },
  {
    pattern: "discovery.ai.rag_query_enabled",
    label: "RAG Query Enabled",
    description: "Allows retrieval-augmented response flows.",
    whyItMatters: "Changes runtime behavior and model usage paths.",
    example: "Use matching profiles to answer freeform discovery prompts.",
    recommendedDefault: "Enabled after prompt/quality validation.",
    riskLevel: "medium",
  },
  {
    pattern: "discovery.ai.follow_up_suggestions",
    label: "Follow-Up Suggestions",
    description: "Shows suggested follow-up prompts in discovery UX.",
    whyItMatters: "Improves user flow but can increase model token usage.",
    example: "Suggest refining by country or certification.",
    recommendedDefault: "Enabled for guided discovery UX.",
    riskLevel: "low",
  },
  {
    pattern: "discovery.ai.profile_retrieval_mode",
    label: "Profile Retrieval Mode",
    description: "Selects hybrid or strict semantic retrieval behavior.",
    whyItMatters: "Affects relevance behavior and dependency on vector search health.",
    example: "rag_strict for semantic-first retrieval.",
    recommendedDefault: "hybrid for rollout safety.",
    riskLevel: "medium",
  },
  {
    pattern: "discovery.ai.rag_failure_behavior",
    label: "RAG Failure Behavior",
    description: "Defines fallback behavior if strict retrieval fails.",
    whyItMatters: "Controls outage experience and operator observability.",
    example: "service_unavailable returns explicit 503.",
    recommendedDefault: "service_unavailable.",
    riskLevel: "medium",
  },
  {
    pattern: "discovery.ai.profile_similarity_threshold",
    label: "Similarity Threshold",
    description: "Minimum similarity score for semantic profile matches.",
    whyItMatters: "Higher thresholds improve precision but may reduce recall.",
    example: "0.25 as an initial balanced threshold.",
    recommendedDefault: "0.20 to 0.35 for initial calibration.",
    riskLevel: "medium",
  },
  {
    pattern: "discovery.ai.max_vector_candidates",
    label: "Max Vector Candidates",
    description: "Maximum number of vector candidates considered before ranking.",
    whyItMatters: "Balances relevance headroom and retrieval latency.",
    example: "500 candidates.",
    recommendedDefault: "200 to 500 for MVP scale.",
    riskLevel: "medium",
  },
  {
    pattern: "profile_schemas.*.sections.*.name",
    label: "Profile Section Name",
    description: "Section heading used to group profile fields.",
    whyItMatters: "Shapes onboarding UX clarity and profile organization.",
    example: "Production Details",
    recommendedDefault: "Short descriptive section names.",
    riskLevel: "low",
  },
  {
    pattern: "profile_schemas.*.sections.*.fields.*.name",
    label: "Field Key",
    description: "Stable field identifier stored in profile payloads.",
    whyItMatters: "Renaming this can break filters, integrations, and generated contracts.",
    example: "certifications",
    recommendedDefault: "snake_case and stable over time.",
    riskLevel: "high",
  },
  {
    pattern: "profile_schemas.*.sections.*.fields.*.label",
    label: "Field Label",
    description: "Human-readable field name displayed in forms and profiles.",
    whyItMatters: "Affects onboarding clarity for users.",
    example: "Certifications",
    recommendedDefault: "Concise, user-facing wording.",
    riskLevel: "low",
  },
  {
    pattern: "profile_schemas.*.sections.*.fields.*.type",
    label: "Field Type",
    description: "Data type used for validation and rendering.",
    whyItMatters: "Changes accepted input shape and generated API models.",
    example: "multi_select",
    recommendedDefault: "Use the simplest type that fits.",
    riskLevel: "high",
  },
  {
    pattern: "profile_schemas.*.sections.*.fields.*.visibility",
    label: "Field Visibility",
    description: "Controls who can view this field (public/protected/private).",
    whyItMatters: "Directly affects privacy and discoverability.",
    example: "protected for sensitive business details.",
    recommendedDefault: "public by default, tighten for sensitive data.",
    riskLevel: "high",
  },
  {
    pattern: "profile_schemas.*.sections.*.fields.*.options",
    label: "Field Options",
    description: "Allowed values for select/multi_select fields.",
    whyItMatters: "Defines canonical category values and filter consistency.",
    example: "Organic, Non-GMO, Fair Trade",
    recommendedDefault: "Short curated list with stable values.",
    riskLevel: "medium",
  },
  {
    pattern: "profile_schemas.*.sections.*.fields.*.required",
    label: "Field Required",
    description: "Whether users must provide this field in onboarding/profile updates.",
    whyItMatters: "Higher required rates improve data quality but can reduce completion.",
    example: "Company name required.",
    recommendedDefault: "Require only high-signal essentials.",
    riskLevel: "medium",
  },
  {
    pattern: "profile_schemas.*.sections.*.fields.*.searchable",
    label: "Field Searchable",
    description: "Whether this field contributes to search/filter behavior.",
    whyItMatters: "Impacts discovery relevance and potential data exposure.",
    example: "Country searchable, internal notes not searchable.",
    recommendedDefault: "Enable for public discovery attributes only.",
    riskLevel: "high",
  },
  {
    pattern: "ai_providers.enabled",
    label: "Enable Provider",
    description: "Enable this provider to make it available for AI features. Set the corresponding API key in your .env file.",
    whyItMatters: "Only enabled providers can be selected for use-case routing via the Admin API.",
    example: "Enable OpenAI if you have an OPENAI_API_KEY set.",
    recommendedDefault: "Enable at least one provider with a configured API key.",
    riskLevel: "medium",
  },
  {
    pattern: "ai_providers.embedding_provider",
    label: "Embedding Provider",
    description: "Embedding is used for all search and RAG features. Pick one provider and keep it consistent — changing it requires re-indexing all documents and profiles.",
    whyItMatters: "The embedding provider determines the vector space all content is indexed in. Switching providers invalidates existing embeddings.",
    example: "OpenAI text-embedding-3-small for cost-effective semantic search.",
    recommendedDefault: "OpenAI for broadest compatibility.",
    riskLevel: "high",
  },
  {
    pattern: "output_path",
    label: "Output Path",
    description: "YAML file path used when saving setup config.",
    whyItMatters: "Defines where canonical configuration is persisted.",
    example: "marketplace.yaml",
    recommendedDefault: "marketplace.yaml in project root.",
    riskLevel: "medium",
  },
  {
    pattern: "apply_runtime",
    label: "Apply Runtime Immediately",
    description: "Applies saved config to current in-process runtime state.",
    whyItMatters: "Can immediately affect live behavior in the current process.",
    example: "Enable during setup testing; disable for save-only workflows.",
    recommendedDefault: "Enabled in setup environment.",
    riskLevel: "high",
  },
  {
    pattern: "compile_mode",
    label: "Compile Mode",
    description: "Determines compiler generation mode.",
    whyItMatters: "Affects generated warnings and target runtime semantics.",
    example: "mvp",
    recommendedDefault: "mvp until strict-mode rollout is complete.",
    riskLevel: "medium",
  },
  {
    pattern: "export_dir",
    label: "Export Directory",
    description: "Directory for generated export archives.",
    whyItMatters: "Controls artifact packaging location and CI handoff path.",
    example: "exports",
    recommendedDefault: "exports.",
    riskLevel: "low",
  },
  {
    pattern: "export_enabled",
    label: "Create Export Archive",
    description: "Creates a tarball snapshot after generation.",
    whyItMatters: "Useful for audits, transfers, and release packaging.",
    example: "Enabled in CI compile jobs.",
    recommendedDefault: "Enabled.",
    riskLevel: "low",
  },
];

export const GLOSSARY_TERMS = [
  {
    term: "Participant role",
    definition: "A user type in your marketplace, such as Producer or Buyer.",
  },
  {
    term: "Approval",
    definition: "Admin review workflow before a profile becomes active.",
  },
  {
    term: "Discovery",
    definition: "Search and filtering behavior used to find profiles.",
  },
  {
    term: "Visibility",
    definition: "Controls who can view profile attributes.",
  },
  {
    term: "Profile schema",
    definition: "Role-specific sections and fields users complete.",
  },
  {
    term: "Generated aliases",
    definition: "Role-specific API endpoints generated from participant slugs.",
  },
];

function normalize(path) {
  return String(path || "").replace(/\.\d+\./g, ".*.").replace(/\.\d+$/g, ".*");
}

function wildcardMatch(pattern, path) {
  const source = pattern
    .replace(/[.+?^${}()|[\]\\]/g, "\\$&")
    .replace(/\*/g, "[^.]+");
  const re = new RegExp(`^${source}$`);
  return re.test(path);
}

export function getFieldHelp(path) {
  const normalized = normalize(path);
  const entry = HELP_ENTRIES.find((item) => wildcardMatch(item.pattern, normalized));
  if (entry) {
    return entry;
  }
  return {
    label: "Configuration Field",
    description: "Adjusts how your marketplace behaves.",
    whyItMatters: "This setting can change onboarding policy or runtime behavior.",
    example: "Use recommended defaults unless you have a clear policy need.",
    recommendedDefault: "Keep defaults first, then tune with evidence.",
    riskLevel: "medium",
  };
}

export function listHelpEntries() {
  return HELP_ENTRIES.slice();
}
