"""E2E: /api/roles/{slug}/... role-alias routes.

These routes are generated by the backend compiler from marketplace.yaml
(``app/generated/role_alias_router.py``) and are the primary public-
facing entry points.  Unlike the generic ``/api/profiles`` routes, these
declare explicit ``response_model``s, so every success response is
validated against its OpenAPI schema.

Coverage (per slug in marketplace.yaml):

- POST /api/roles/{slug}/register
- GET  /api/roles/{slug}/draft
- PUT  /api/roles/{slug}/draft
- POST /api/roles/{slug}/draft/submit
- GET  /api/roles/{slug}/me
- GET  /api/roles/{slug}/{profile_id}
- PUT  /api/roles/{slug}/{profile_id}
- POST /api/roles/{slug}/{profile_id}/ai-generate
- POST /api/roles/{slug}/{profile_id}/ai-approve
- POST /api/roles/{slug}/{profile_id}/ai-reject
"""

from __future__ import annotations

import httpx
import pytest

from tests.e2e.contract import ContractClient, OpenAPIContract


@pytest.mark.e2e
@pytest.mark.asyncio
async def test_buyer_alias_draft_roundtrip(
    buyer_client: dict,
    openapi_contract: OpenAPIContract,
) -> None:
    client: httpx.AsyncClient = buyer_client["client"]
    c = ContractClient(client, openapi_contract)

    r_draft = await c.get("/api/roles/buyer/draft", expected_status=(200, 404))
    assert r_draft.status_code in (200, 404)

    r_update = await c.put(
        "/api/roles/buyer/draft",
        json={
            "fields": {
                "org_name": "Alias Org",
                "country": "Canada",
                "business_type": "Mill",
            }
        },
        expected_status=(200, 404),
    )
    assert r_update.status_code in (200, 404)


@pytest.mark.e2e
@pytest.mark.asyncio
async def test_alias_draft_validates_contract(
    onboarded_buyer: dict,
    openapi_contract: OpenAPIContract,
) -> None:
    client: httpx.AsyncClient = onboarded_buyer["client"]
    c = ContractClient(client, openapi_contract)
    r = await c.get("/api/roles/buyer/me", expected_status=(200, 404))
    assert r.status_code in (200, 404)


@pytest.mark.e2e
@pytest.mark.asyncio
async def test_alias_routes_require_auth(
    anonymous_client: httpx.AsyncClient,
) -> None:
    for method, path in (
        ("GET", "/api/roles/buyer/draft"),
        ("PUT", "/api/roles/buyer/draft"),
        ("POST", "/api/roles/buyer/draft/submit"),
        ("GET", "/api/roles/buyer/me"),
        ("GET", "/api/roles/producer/draft"),
    ):
        r = await anonymous_client.request(method, path, json={})
        assert r.status_code == 401


@pytest.mark.e2e
@pytest.mark.asyncio
async def test_alias_admin_actions_require_admin(
    buyer_client: dict,
) -> None:
    client: httpx.AsyncClient = buyer_client["client"]
    fake_id = "00000000-0000-0000-0000-000000000000"

    r_approve = await client.post(f"/api/roles/buyer/{fake_id}/ai-approve")
    assert r_approve.status_code == 403

    r_reject = await client.post(f"/api/roles/buyer/{fake_id}/ai-reject")
    assert r_reject.status_code == 403


@pytest.mark.e2e
@pytest.mark.asyncio
async def test_producer_alias_registration_parity(
    onboarded_producer: dict,
    openapi_contract: OpenAPIContract,
) -> None:
    client: httpx.AsyncClient = onboarded_producer["client"]
    c = ContractClient(client, openapi_contract)
    r = await c.get("/api/roles/producer/me", expected_status=(200, 404))
    assert r.status_code in (200, 404)
